#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package pkgbuild;

class pkgbuild : does(BS::Common);

use utf8;
use v5.40;

use Getopt::Long 'GetOptionsFromArray';

#use BS::Common;
use BS::Package;
use BS::Ext::expac;
use BS::Ext::pacsift;
use BS::Ext::pactree;

field $argv : param = \@ARGV;
field $runopts : param(dest) = {};
field $pkgin : param : reader = [];

ADJUSTPARAMS($params) {
    GetOptionsFromArray(
        $argv, $runopts,
        'build-tree=i',
        'target-architectures=s',
        'makefile-conf=s',
        'pacman-conf=s',
        'prefer-vcs',
        '!verbose+',
        '<>' => sub ($barearg) {
            my $pkg = BS::Package->parse_pkgstr($barearg);
            dmsg( { pkg => $pkg, barearg => $barearg } );
            push @$pkgin, $pkg;
        }
    );

    dmsg( { argv => $argv, runopts => $runopts, pkgin => $pkgin } )
}

method run : common (%opts) {
    my $self = $class->new( %opts{qw(argv dest)} );
    dmsg( { self => $self } );
    $self;
}

package main;

class main;

use Data::Dumper;

sub run {
    my $pkgbuild = pkgbuild->run( argv => \@ARGV );
    warn Dumper($pkgbuild);
}

run

# perl -MData::Dumper -e 'use v5.40; use List::Util "uniq"; say join " ", uniq map { chomp $_; split /[\r\n]+/ } (@ARGV)' $(expac -S '%e' $(arch-rebuild-order --no-reverse-depends --repos=universe,core,extra  $(perl -MData::Dumper -e 'use v5.40; use List::Util "uniq"; say join "\n", uniq map { chomp $_; split /[\r\n]+/ } (@ARGV)'  $(expac -S '%n' $(pactree -lus gnome-boxes)))))

