#!/usr/bin/env perl

package alpmtest;

use utf8;
use v5.40;

use lib 'lib';

use BS::alpm;
use File::Temp;
use Path::Tiny;
use Data::Printer;
use Syntax::Keyword::Try;

our $alpmabs = path('./src/pacman/lib/libalpm')->absolute;
our $combfile;

BEGIN {
  our $combstr = "";
  $combfile = File::Temp->new();
  $alpmabs = path('./src/pacman/lib/libalpm')->absolute;

  foreach my $h (path('./src/pacman/lib/libalpm')->children(qr/alpm_list\.h\z/)) {
    next unless $h isa 'Path::Tiny';
    my $hsrc = $h->slurp_utf8 . "\n";
    #$hsrc =~ s/.*include.*//g;
    $combstr .= $hsrc
  }

  $combstr .= path('./src/pacman/lib/libalpm/alpm_list.h')->slurp_utf8;
  $combstr .= path('./src/pacman/lib/libalpm/alpm.h')->slurp_utf8;
  $combstr .= q{typedef struct _alpm_list_t {
	/** data held by the list node */
	void *data;
	/** pointer to the previous node */
	struct _alpm_list_t *prev;
	/** pointer to the next node */
	struct _alpm_list_t *next;
} alpm_list_t;};

  
  #foreach my $h (path('./src/pacman/lib/libalpm')->children(qr/(alpm)\.c\z/)) {
  #  next unless $h isa 'Path::Tiny';
  #  my $hsrc = $h->slurp_utf8 . "\n";
  #  $hsrc =~ s/.*include.*/\n/g;
  #  $combstr .= $hsrc
  #}

  say $combstr if $ENV{DEBUG};

  path($combfile->filename)->spew_utf8($combstr);
}

use Inline C => Config => LIBS => "-L$alpmabs -lalpm";

use Inline C => path($combfile)->absolute
  , enable => 'autowrap',
  , INC => path('./src/pacman/')->absolute;

  use Inline C => "alpm_handle_t *alpm_initialize(const char *root, const char *dbpath);"
  , enable => 'autowrap',
  , INC => path('./src/pacman/')->absolute;
  #, myextlib => '/usr/lib/libalpm.so.15',
  #, libs => '-lalpm -lalpm_list -lalpm_depends -lalpm_packages',
  #, INC => path('./src/pacman/')->absolute;

#unlink path('./src/pacman/lib/libalpm/combined.h')->absolute;

use Data::Dumper;
use Data::Printer;

sub new {
  bless {}, __PACKAGE__
}

sub hi ($self) {
  
  try {
    alpmtest::alpm_initialize()
  }
  catch ($e) {
    p $e
  }

  p $self
}
1;

#package main;
#use alpmtest;

my $obj = alpmtest->new;

$obj->hi
