#!/usr/bin/env bash
[[ "${DEBUG:-0}" -ne 0 ]] && set -x

scriptdir="${0//\/$(basename "$0")/}"
. "$scriptdir/bs-common.sh"

repo="${BS_REPO:-universe}"
repodir="$BS_REPOROOT/$repo/os/$BS_TARGET/"
repodb="$repodir/$repo.db.tar.zst"
gpgpubid="${BS_GPGID:-${BS_GPGFPR:-${BS_GPG_PUBID:-${GPGKEYID}}}}"
pkgdest="${BS_PKGDEST:-${PKGDEST:-"$BS_ROOT/pkgdest"}}"

pkgs=("$@")
user="$(whoami)"
targetcarch="${TARGET_CARCH:-${CARCH:-$(uname -m)}}"
chroot="${CHROOT:-/var/lib/bs/chroot/$targetcarch}"

hostfqdn=$(
	perl -Mv5.40 -MNet::Domain \
		-e 'say Net::Domain::hostfqdn || Net::Domain::domainname;'
)

[[ ${#pkgs} -eq 0 ]] && pkgs=("$(basename "$(pwd)")")
pkginstr="${pkgs[*]}"

echo -e "▶ Building the following packages:\n$pkginstr\n"

if [[ -z "$WKCHROOT" ]] || [[ ! -d "$WKCHROOT" ]]; then
	WKCHROOT="$user@$hostfqdn-$1+${#@}-$(date +%s)"
fi

say() {
	for msg in "$@"; do
		echo -e "▶ $msg"
	done
}

warn() {
	perl -Mv5.40 -Mutf8 -e 'say STDERR "❌️ $_" for (<>)' "$@"
}

err() {
	status="$?"
	msg=("$@")
	warn "${msg[@]}" && exit $status
}

success() {
	perl -Mv5.40 -Mutf8 -e 'say "◯ $_" for (<>)' "$@"
}

pkgtree() {
	pkgptn=("$@")
	pkgname_toplvl=()

	for ptn in "${pkgptn[@]}"; do
     pkgname_toplvl+=($(expac -Ss '%n' "$ptn"))
	done

	
# perl -Mv5.40 -MList::Util=uniw -e 'say join " ", uniq map { split /[\s\r\n]/ } map { `expac -S "%e" $_` } map { say STDERR $_; `arch-rebuild-order --no-reverse-depends  $_` } join " ", =uniq map {  say STDERR $_; chomp $_; $_ } map {   say STDERR $_;  `expac -S "%n" $_` } join " ", uniq grep { $_ ne "" && $_ !~ /lib32|-git/ } map { chomp $_; $_ } map { split /[\s\n\r]/, $_ } map { `expac -Ss "%e %n %D" "$_"` } @ARGV'

 perl -Mv5.40 -MList::Util=uniq -e 'say join " ", map { `arch-rebuild-order --no-reverse-depends --repos=universe,core,extra,multilib $_` } join " ", uniq map { chomp $_; $_ } map { `expac -S "%n" $_` } join " ", uniq  map { chomp $_; qq{"$_"} } map { chomp $_; `pactree -lus "$_"` } map { `expac -Ss "%n" $_` } (@ARGV)' "${pkgptn[@]}"

 return $?



	# #for pkg in $pkgname_toplvl; do
	#   DEBUG=1 perl -Mv5.40 -d:Trace -MBS::Common \
	#    -e 'use List::Util "uniq"; use v5.40; say map { BS::Common::dmsg({"$_" => $_}); chomp $_; `arch-rebuild-order --no-reverse-depends --repos=universe,core,extra,multilib $_` } join " ", uniq grep { ! /lib32/ } map { chomp $_; $_; } map { chomp $_; `expac -S "%n" "$_"` }  map { chomp $_; `pactree -lus "$_"` } map { (split /\s+/ $_ )} (@ARGV)' -- 
	# 	 perl -e 'join " ", map { split [/s\n\r]/+ } (@ARGV)' "${pkgname_toplvl[@]}"
}

moveclone() {
	for pkg in "$@"; do
		[[ -d "/bs/cgit/pennylinux/pkgbuild/work/$pkg" ]] ||
			(
				echo "▶ Copying package from import directory '$IMPORTDIR'."
				cp -vaf "/bs-old/pkgbuild.1/$pkg" \
					"/bs/cgit/pennylinux/pkgbuild/work" &&
					return 0
			)

		[[ -d "/bs/cgit/pennylinux/pkgbuild/work/$pkg" ]] ||
			(echo "▶ Cloning official repo:" &&
				pkgctl repo clone --protocol https "$pkg")
	done
}

source_pkgbuild () {
	pkgbuild="$1"
	
	[[ "${SOURCE_PKGBUILD:-0}" ]] \
			&& >&2 echo -e "Sourcing PKGBUILD file instead of .SRCINFO. Be adviced this may very well be dangerous to run outside of a container.\n\nTODO: Ask user (you/me?) if they want to exit." \
			&& echo -e "eval the following line to finalize importing its environment post-load:\n\n . $pkgbuild" \
			&& . "$pkgbuild"

	return $?
}

rebasebuild() {
	for pkg in "$@"; do
		cwd="$(basename "$(pwd)")"

		if [[ -n "${cwd//$(basename "$pkg")/}" ]]; then
			cd "$pkg" || continue #continue
		fi

    [[  ${DEBUG:-0} -eq 1 ]] && set -x
    
		pkgbuildeval=$(source_pkgbuild "./PKGBUILD")
		eval "${pkgbuildeval[*]:${#pkgbuildeval[*]}:1}"

   	[[  ${DEBUG:-0} -eq 1 ]] && set +x
		[[  ${DEBUG:-0} -ne 0 ]] && printenv

		commit="${source//*commit=/}/}"

		[[ -n "${MERGETOOL}" ]] && git config merge.tool "$MERGETOOL"

		say "Updating .SRCINFO and committing changes since last pull..."
		makepkg --printsrcinfo >.SRCINFO
		git add PKGBUILD .SRCINFO
		git commit -S -m '...'

		say "Rebasing. You will be prompted if there are any conflicts."
		git pull --rebase
		rebaseexit="$?"

		while [[ "$rebaseexit" -ne 0 ]]; do
			git mergetool
			git rebase --continue
			rebaseexit="$?"
			[[ "$rebaseexit" -eq 128 ]] && break
		done

		say "Opening current PKGBUILD for viewing and final edits. Please review it closely!\n"
		nvim PKGBUILD

		# . .SRCINFO
		# commit_postrebase="${source//*commit=/}/}"

		# if [[ -z "$(perl -Mv5.40 -e \
		# 	'say (s/.*commit=([a-z0-9]{41})/$1/r)[0]')" ]]; then
		# 	echo "▶ New commit detected in source array URL!"
		# 	echo "▶ Updating checksums..."
		# 	updpkgsums
		# fi

		say "Building '$pkg' in '$chroot/$WKCHROOT'"
		makechrootpkg -Cun -r"$chroot" ${WKCHROOT:+-l"$WKCHROOT"} - -Lisf

		say "Signing and adding '$pkg' to '$BS_REPO'"
		bs-repoadd \
			"${pkgdest:?}/"*.pkg.tar.zst # $(srcinfo --fields pkgname --format glob)

		say "Removing copied artifacts and pacman cache (to avoid duplicate packages from the official repos)"
		paccache -rk0

		[[ ${CLEAN_PKGDEST:-0} -eq 1 ]] &&
			rm -r "${pkgdest:?}/"*

		cd ..
	done
}

moveclone "${pkgs[@]}"
rebasebuild "${pkgs[@]}"
