#!/usr/bin/env bash
[[ "${DEBUG:-0}" -ne 0 ]] && set -x

scriptdir="${0//\/$(basename "$0")/}"
. "$scriptdir/bs-common.sh"

repo="${BS_REPO:-universe}"
repodir="$BS_REPOROOT/$repo/os/$BS_TARGET/"
repodb="$repodir/$repo.db.tar.zst"
gpgpubid="${BS_GPGID:-${BS_GPGFPR:-${BS_GPG_PUBID:-${GPGKEYID}}}}"
pkgdest="${BS_PKGDEST:-${PKGDEST:-"$BS_ROOT/pkgdest"}}"

pkgs=("$@")
user="$(whoami)"
targetcarch="${TARGET_CARCH:-${CARCH:-$(uname -m)}}"
chroot="${CHROOT:-/var/lib/bs/chroot/$targetcarch}"

hostfqdn=$(
	perl -Mv5.40 -MNet::Domain \
		-e 'say Net::Domain::hostfqdn || Net::Domain::domainname;'
)

[[ ${#pkgs} -eq 0 ]] && pkgs=("$(basename "$(pwd)")")
pkginstr="${pkgs[*]}"

echo -e "▶ Building the following packages:\n$pkginstr\n"

if [[ -z "$WKCHROOT" ]] || [[ ! -d "$WKCHROOT" ]]; then
	WKCHROOT="$user@$hostfqdn-$1+${#@}-$(date +%s)"
fi

say() {
	for msg in "$@"; do
		echo "▶ $msg"
	done
}

warn() {
	perl -Mv5.40 -Mutf8 -e 'say STDERR "❌️ $_" for (<>)' "$@"
}

err() {
	status="$?"
	msg=("$@")
	warn "${msg[@]}" && exit $status
}

success() {
	perl -Mv5.40 -Mutf8 -e 'say "◯ $_" for (<>)' "$@"
}

moveclone() {
	for pkg in "$@"; do
		[[ -d "/bs/cgit/pennylinux/pkgbuild/work/$pkg" ]] ||
			(
				echo "▶ Copying package from import directory '$IMPORTDIR'."
				cp -vaf "/bs-old/pkgbuild.1/$pkg" \
					"/bs/cgit/pennylinux/pkgbuild/work" &&
					return 0
			)

		[[ -d "/bs/cgit/pennylinux/pkgbuild/work/$pkg" ]] ||
			(echo "▶ Cloning official repo:" &&
				pkgctl repo clone --protocol https "$pkg")
	done
}

rebasebuild() {
	for pkg in "$@"; do
		cwd="$(basename "$(pwd)")"

		if [[ -n "${cwd//$(basename "$pkg")/}" ]]; then
			cd "$pkg" || continue #continue
		fi

		commit="${source//*commit=/}/}"

		[[ -n "${MERGETOOL}" ]] && git config merge.tool "$MERGETOOL"

		say "Updating .SRCINFO and committing changes since last pull..."
		makepkg --printsrcinfo >.SRCINFO
		git add PKGBUILD .SRCINFO
		git commit -S -m '...'

		say "Rebasing. You will be prompted if there are any conflicts."
		git pull --rebase
		rebaseexit="$?"

		while [[ "$rebaseexit" -ne 0 ]]; do
			git mergetool
			git rebase --continue
			rebaseexit="$?"
			[[ "$rebaseexit" -eq 128 ]] && break
		done

		say "Opening current PKGBUILD for viewing and final edits. Please review it closely!\n"
		nvim PKGBUILD

		# . .SRCINFO
		# commit_postrebase="${source//*commit=/}/}"

		# if [[ -z "$(perl -Mv5.40 -e \
		# 	'say (s/.*commit=([a-z0-9]{41})/$1/r)[0]')" ]]; then
		# 	echo "▶ New commit detected in source array URL!"
		# 	echo "▶ Updating checksums..."
		# 	updpkgsums
		# fi

		echo "▶ Building '$pkg' in '$chroot/$WKCHROOT'"
		makechrootpkg -Cun -r"$chroot" ${WKCHROOT:+-l"$WKCHROOT"} - -Lisf

		echo "▶ Signing and adding '$pkg' to '$BS_REPO'"
		bs-repoadd \
			"${pkgdest:?}/"*.pkg.tar.zst # $(srcinfo --fields pkgname --format glob)

		echo "▶ Removing copied artifacts and pacman cache (to avoid duplicate packages from the official repos)"
		paccache -rk0

		[[ ${CLEAN_PKGDEST:-0} -eq 1 ]] &&
			rm -r "${pkgdest:?}/"*

		cd ..
	done
}

moveclone "${pkgs[@]}"
rebasebuild "${pkgs[@]}"
