#!/usr/bin/env perl

use Object::Pad ':experimental(:all)';

package bs_pacman;

class bs_pacman;

use utf8;
use v5.40;

no warnings 'experimental::re_strict';
use re 'strict';

use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case auto_abbrev long_prefix_pattern=--?);
use Const::Fast;
use List::Util qw'first uniq none';
use IPC::Nosh  qw'';
use IO::Handle::Common;

const our @REPO_DEFAULT => qw(
  universe
  core
  extra
);

const our %RUN_DEFAULT => (
    autochomp => 1,
    err       => sub ( $line, @ ) {
        say STDERR $line;
    }
);
const our $soname_re => qr/(.+\.so)=([0-9-].+)/xx;
const our $ver_req   => qr/([=<>]{1}|(?:[<>]=)){,2}/x;

const our $pkgname_re => qr/
([a-z0-9_@+][a-z0-9_@+.-]+)
 (?:
   ([\s-]|[=<>]{1}|[<>]=)
   ([^\s:\/\\-]+?)
 )?/xi;

const our @pacenv => map { ( $_ = s/PACMAN_//r, $_ ) } qw(
  REFRESH REGEX OVERWRITE NEEDED NO_CONFIRM NODEPS ROOT VERBOSE ARCH COLOR CONFIRM SYSROOT DBPATH CACHEDIR PACMAN_OPT
);

const our $envparam_map =>
  ( map { lc($_) =~ s/PACMAN_?//r =~ s/_/-/r } @pacenv );

const our $pacman_defaultarg => qw(--overwrite * --no-confirm -dd);

method $run (%opt) {
    my @pacman_cmd = qw(pacman -S);

}

method pacman : common ($argv = \@ARGV) {
    my $self = $class->new(@$argv);
    $self->$run;
}

package bs_pacman::CLI;

use utf8;
use v5.40;

sub cli ( $argv = \@ARGV ) {
    my %clidest = ( in => [], prune => 'input', sep => ' ' );

    GetOptionsFromArray(
        $argv,
        \%clidest,

        # output verbosity control
        'debug+',
        'verbose+',
        'quiet+',

        # prune/filter packages at different stages of resolution
        "prune-input:s@",
        "variant|choose|chosen|wanted:s@",

        # input packages
        '<>' => sub ($barearg) {
            push $clidest{in}->@*, $barearg;
        }
    );

    my $self = bs_pacman->new(%clidest);

    my @pkgtree = $self->resolve;

}
bs_pacman->cli( \@ARGV )
