#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';
use Object::Pad::FieldAttr::Trigger;

package App::BS::CLI::pacman;

class App::BS::CLI::pacman : does(BS::Common);

use utf8;
use v5.40;

use lib 'lib';

use IPC::Run3;
use Const::Fast;
use Syntax::Keyword::Try;
use Syntax::Keyword::Dynamically;
use Stream::Buffered;
use IO::Handle;

use BS::Common 'dmsg';

const our $S_IPCRUN3_FATAL => sub (%opt) {
    use Data::Dumper;
    "❌️ Unrecoverable error while spawning external command!\n"
      . Dumper( $opt{e} );
};

field $cliopts : param(dest) = { verbose => 1 };
field $env : param : reader = { %ENV{qw'as_needed debug verbose'} };

field $status : reader;
field $errmsg : reader;
field $out_aref = [];
field $err_aref = [];

method $run (%opts) {

    # Why am I using Syntax::Keyword::Dynamically over local outside of suppport
    # for Ojbect::Pad?
    dynamically $status   = 0;
    dynamically $errmsg   = "";
    dynamically $out_aref = [];

    my @overwrite = $ARGV[0] eq '-S' ? qw(--overwrite '*' --noconfirm) : ();
    push @overwrite, '--needed' if $$env{as_needed};

    try {
        # Avoid delays in relaying output
        # my $stdout = select(STDOUT);
        # $|++;
        # select(STDERR);
        # $!++;
        # select($stdout);

        my $inh = IO::Handle->new_from_fd( fileno(STDIN), "r" );
        $inh->autoflush(1);
        my $outh = IO::Handle->new_from_fd( fileno(STDOUT), "w" );
        my $errh = IO::Handle->new_from_fd( fileno(STDERR), "w" );

        tie @$out_aref, 'Tie::File', $outh;
        tie @$errh,     'Tie::File', $errh;

        my $ret = run3( [ 'pacman', @overwrite, '--verbose', @ARGV ],
            $inh, $out_aref, $err_aref );

        ( $status, $errmsg ) =
          $? != 0 ? ( $?, $! ) : ( 0, '', $$err_aref[ scalar @$err_aref ] );

        BS::Common::dmsg(
            {
                overwrite => \@overwrite,
                ret       => $ret,
                errmsg    => $errmsg,
                status    => $status,
                opts      => \%opts
            }
        )
    }
    catch ($e) {
        die $S_IPCRUN3_FATAL->( e => $e );
    }
    finally {
        chomp $errmsg;
        $errmsg =~ s/^(.+)[\s\r\n]*/$1/g;

        BS::Common::dmsg(
            { errmsg => $errmsg, status => $status, opts => \%opts } )
    };

    $status ? 0 : 1;
}

method run : common ($argv, %opts) {
    my $app  = $class->new( argv => $argv, %opts{qw''} );
    my $exit = $app->$run;
    $app;
}

package main;

use v5.40;

use BS::Common 'dmsg';

sub run {
    our $app = App::BS::CLI::pacman->run( \@ARGV );
    BS::Common::dmsg( { app => $app } );
}

run
