#!/usr/bin/env perl

use utf8;
use v5.40;

use lib 'lib';

use BS::Common;
use Data::Dumper;
use IPC::Run3;

if ( $ENV{DEBUG} ) {
    warn Dumper( { argv => \@ARGV } );
}

my @out;
my @overwrite = $ARGV[0] eq '-S' ? qw(--overwrite '*' --noconfirm) : ();
push @overwrite, '--needed' if $ENV{ASNEEDED};

my $ret = run3(
    [ 'pacman', @overwrite, '--verbose', @ARGV ],
    undef,
    sub { say @_; push @out, $_[0] },
    sub { warn @_; }
);

my $status = $?;

if ( $ENV{DEBUG} ) {
    BS::Common->dmsg(
        overwrite => \@overwrite,
        status    => $status,
        ret       => $ret,
        out       => \@out
       )
    );
}

exit $status
