#!/usr/bin/env perl

# This chunk of stuff was generated by App::FatPacker. To find the original
# file's code, look for the end of this BEGIN block or the string 'FATPACK'
BEGIN {
my %fatpacked;

$fatpacked{"App/BS.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS';
  use Object::Pad qw(:experimental(:all));
  
  package App::BS;
  
  use constant VERSION => "0.01";
  
  class App::BS; #: does(App::BS::Common);
  
  use utf8;
  use v5.40;
  
  use TOML::Tiny 'from_toml';
  use Const::Fast;
  use Const::Fast::Exporter;
  use Syntax::Keyword::Try;
  
  our $VERSION = VERSION;
  
  method $import : common (@args) {
      use utf8;
      use v5.40;
  };
  
  ADJUSTPARAMS($params) {
      __CLASS__->$import($params)
  };
  
  try {
      use BS::Common;
      use App::BS::Common;
      my ( $toml, $error ) => from_toml($App::BS::defaultconfig_inline);
      die $error if $error;
      const our $config_default => $toml
  }
  catch ($e) {
      BS::Common::dmsg { err => $e }
  }
  
  const our $defaultconfig_inline => <<'...';
  #
  # Default/Test Configuration Schema
  #
  
  [example_document]
    # This is a TOML document
    title = "TOML Example"
  
    [owner]
      name = "Tom Preston-Werner"
      dob = 1979-05-27T07:32:00-08:00
  
    [database]
        enabled = true
        ports = [ 8000, 8001, 8002 ]
        data = [ ["delta", "phi"], [3.14] ]
        temp_targets = { cpu = 79.5, case = 72.0 }
  
    [servers]
  
    [servers.alpha]
      ip = "10.0.0.1"
      role = "frontend"
  
    [servers.beta]
      ip =   "10.0.0.2"
      role = "backend"
  
  [bs] # The "bs" section heading can be omitted for global/top-level options
      root = "/bs"
      user = "bu"
      group = "alpm"
      targets = [
        "thanksmom-mba52", "cincotuf"
      ]
  
  [targets.thanksmom-mba52]
      carch = "x86_64"
      ip = "192.168.86.152"
      domain = "lan"
  
  [pkgbase]
      resolution_order = [ 'local', 'repo' ]
      resolution_order.repo = [ 'pacman.conf' ]
  
  [pkgbuild]
      root = "/bs" # You can (re-)configure many top-level options for each section
                  # idividually
      debug = 1
      clean_chroot = 1
      makepkg_clean_all = 1 # Equivalent to adding C,c to makepkg_args for now
      chroot => "$root/"
  
  [repo]
      [universe]
          target_arch = [ "x86_64", "x86_64_v3", "aarch64" ]
          siglevel = [ 'DatabaseOptional', 'PackageTrustedOnly' ]
  
          # There are plently of helper preset variables to keep your config
          # consise, and easy to parse/decontstruct progmatically
          server = "file://$sroot/repo/$repo/os/$arch"
  ...
  
  __END__
  
  =encoding utf-8
  
  =head1 NAME
  
  App::BS - Build system for PKGBUILD based Linux distributions
  
  =head1 SYNOPSIS
  
  Using BS in your own script:
  
  	use ut8;
  	use v5.40;
  
  	use BS;
  	...
  
  Update and rebuild your entire toolchain recursively. This is expected to
  perform each operation such that the conditions outlined i
  https://wiki.archlinux.org/title/DeveloperWiki:Toolchain_maintenance are properly met:
  
  	$ pkgbuild -r gcc llvm clang lld rustc go
  	pkgbuild queue: linux-api-headers glibc binutils gcc glibc binutils gcc llvm clang lld rustc go
  	...
  
  =head1 DESCRIPTION
  
  App::BS is a Perl distribution providing a set of integrated build tools and helpers for already existing tools on Arch Linux and closely-related distributions. It aids creating installable package files for any repository or directory containing a valid PKGBUILD, whether sourced from AUR, Arch Linux or your distribution's official package repositories, or a local path. Simply provide a package name or some sort of identifier such as a file within or a provided shared object to `bs` with your operation of choice or one of the operation specific scripts such as `pkgbuild`, `pkgdepends`, `pkgprovides` `srcinfo`, etc. and it will search for a matching package base in every enabled source, with priority determined order defined from your configuration file(s), environment or CLI arguments. Before any serious operation, the user is presented each relevant PKGBUILD in a pager (`vfim`) for review if updated or being viewed for the first time, and packages are built in a clean CHROOT by default unless configured otherwise (see: `--keep-clean`, `--start-clean`, `--makepkg-cleanall`, `--makechrootpkg-clean`)
  
  =head1 LICENSE
  
  Copyright (C) Ian P Bradley.
  
  This library is free software; you can redistribute it and/or modify
  it under the same terms as Perl itself.
  
  =head1 AUTHOR
  
  Ian P Bradley E<lt>ian.bradley@studiocrabapple.comE<gt>
  
  =cut
APP_BS

$fatpacked{"App/BS/CLI.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS_CLI';
  use Object::Pad ':experimental(:all)';
  
  package App::BS::CLI;
  
  class App::BS::CLI : does(App::BS::Common);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use Pod::Usage;
  use Const::Fast;
  use Data::Dumper;
  use Getopt::Long qw(GetOptionsFromArray :config auto_abbrev permute bundling);
  
  const our $S_MULTI_BAREARG => "Two bare argument handlers are defined. Please"
    . " remove either 'getopts->{\"<>\"}' or 'handle_bareargs' in 'new'.";
  
  field $bareargs        : param(argv) : mutator(argv);
  field $handle_bareargs : param = undef;
  field $getopts_setup   : param(clispec) : mutator;
  field $cliopts         : param(dest)    : mutator = {};
  
  ADJUSTPARAMS($params) {
      say STDERR Dumper( { params => $params } );
      my @handle_bareargs_arr;
      my $has_bareargs_handler = 0;
  
      if ( $handle_bareargs && ref $handle_bareargs eq 'CODE' ) {
          push @handle_bareargs_arr, $handle_bareargs;
      }
  
      if ( $self->DOES('App::BS::CLI::Barearg') ) {
          push @handle_bareargs_arr, sub { $self->handle_barearg(@_) }
      }
  
      my @_getopts_processed = ();
  
      foreach my ( $name, $val ) ( $self->getopts_setup->@* ) {
          if ( $name eq '<>' && ref $val eq 'CODE' ) {
              push @handle_bareargs_arr, sub { $self->handle_barearg(@_) };
              last;
          }
  
          push @_getopts_processed, grep { $_ } $name, $val;
      }
  
      my $bareword_handler = sub ($arg) {
          foreach my $handler (@handle_bareargs_arr) {
              last if $handler->($arg);
          }
      };
  
      GetOptionsFromArray(
          $self->argv, $self->cliopts, @_getopts_processed,
          '<>', $self->$bareword_handler,
          "debug+",
          "version" => sub { Getopt::Long::VersionMessage(@_) },
          "help"    => sub { Getopt::Long::HelpMessage(@_) }
      )
  }
APP_BS_CLI

$fatpacked{"App/BS/CLI/Barearg.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS_CLI_BAREARG';
  use Object::Pad qw(:experimental(:all));
  
  package App::BS::CLI::Barearg;
  role App::BS::CLI::Barearg;
  
  use utf8;
  use v5.40;
  
  method handle_barearg : required
APP_BS_CLI_BAREARG

$fatpacked{"App/BS/CLI/Util.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS_CLI_UTIL';
  use Object::Pad qw(:experimental(:all));
  
  package App::BS::CLI::Util;
  role App::BS::CLI::Util : does(App::BS::Common);
  
  use utf8;
  use v5.40;
APP_BS_CLI_UTIL

$fatpacked{"App/BS/Common.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS_COMMON';
  use Object::Pad;
  
  package App::BS::Common;
  role App::BS::Common : does(BS::Common) : does(BS::Path);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use IPC::Run3;
  use TOML::Tiny;
  use Const::Fast;
  use List::Util qw(uniq any);
  use Struct::Dumb;
  use Syntax::Keyword::Dynamically;
  use Exporter;
  
  const our $DEFAULT_ENVPREFIXRE => qr/^(?:BS_)?(.+)/;
  const our $DEFAULT_CONFIGPATH  => '/etc/bs/config.toml';
  
  field $config_path : param(config) : mutator =
    [ BS::Path->path($DEFAULT_CONFIGPATH) ];
  
  field $config;
  
  field $aliases = {};
  field $queue : mutator = ();
  
  field $env : mutator = {
      pkgext              => '.pkg.tar.zst',
      debug               => 0,
      charset             => 'utf-8',
      default_config_path => $DEFAULT_CONFIGPATH,
  
      # arch => $env->%{enabled_targets} // [ $env->{target} // $ENV{CARCH}
      #       // qw(x86_64 x86_64_v3 aarch64 armv7l) ]
  };
  
  ADJUST {
      use utf8;
      use v5.40;
      $ENV{DEBUG} = $self->debug = $BS::Common::DEBUG
  };
APP_BS_COMMON

$fatpacked{"App/BS/pkgbuild.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS_PKGBUILD';
  use Object::Pad ':experimental(:all)';
  
  package App::BS::pkgbuild;
  
  class App::BS::pkgbuild : isa(App::BS::CLI);
  
  use utf8;
  use v5.40;
  
  use BS::Common;
  use BS::Ext::expac;
  use BS::Ext::pacsift;
  use File::chdir;
  use List::Util qw(all uniqstr);
  
  # This will probably satisify BS::Package's constructor args with we keep
  # either of them around
  class PKGBUILD::Stub : does(BS::Common) {
  
      field $pkgbase : param : reader = '';
  
      field $pkgname_param : param;
      field @pkgname : reader = ();
  
      field $pkgver : param : reader  = '';
      field $pkgdesc : param : reader = '';
      field $source : param           = [];
  
      field $pkgres : param;    # R
  };
  
  class PKGBUILD::Results : does(BS::Common) {
      field @results     = ();
      field %pkgbase_res = ();
  
      method first ( $by, $name ) {
  
      }
  };
  
  class PKGBUILD::Builder : does(BS::Common) : does(BS::Package::Meta) {
      field $pkgbuild : param : reader = '';
      field $pkgres : param : reader   = ();
  };
  
  field @queue;
  
  #field @pkgres = ();    # This should probably be a hash of some sort?
  #                       # Need to think about how many could be cached
  #                       # per build tree
  
  #field $current_pkgres : reader;
  
  #method add_pkgres($pkgres, %opts) {
  #    #push @pkgres, $pkgres;
  #}
  
  #method pkgres_rm ($pkgres, %opts) {
  #  die unless $pkgres isa PKGBUILD::STUB &&  all {... }
  #    $pkgres->fields->@{qw(pkgname source checksums)}}
  #}
  
  method fetch_aur_pkg : common ($pkgbase, %opts) {
  
  }
  
  method sync_pkgbuild : common ($repo, $pkgbase, %opts) {
  
  }
  
  method query_expac : common ($pkgstar, $userrepo_aref,%opts ) {
  
  }
  
  # These aren't separately named because of an Object::Pad restriction, but to
  # better get across in very few words the differences and implications of using
  # either
  
  #method select_pkgres : common (%opts) {
  
  #}
  
  #method $select_pkgres (%opts) { return $$pkgres{} };
  
  method change_pkgres(%opts) {
      ...
  
      # Will probably remain instance method since non-interactive/declarative
      # builds are planned for the first release
  }
  
  #method run : common ($pkgstr, $constructor_opts //= {}, %run_opts //= ()) {
  #    ...;
  #}
APP_BS_PKGBUILD

$fatpacked{"App/BS/pkgdepends.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_BS_PKGDEPENDS';
  use Object::Pad ':experimental(:all)';
  
  package App::BS::pkgdepends;
  
  class App::BS::pkgdepends
    : isa(App::BS::CLI);
  
  use BS::Ext::pactree;
  use BS::Ext::expac;
  
  use utf8;
  use v5.40;
  
  field $queue : mutator : param = [];
  
  method run (%runopts) {
      $self->print_self if $ENV{DEBUG};
  
      foreach my $pkg (@$queue) {
          state $sync = $self->cliopts->{sync};
  
          print __CLASS__->list_deps(
              $pkg, $self->cliopts->%*, %runopts, sync => $sync
            ),
            $pkg ne $$queue[-1]
            ? ( $self->cliopts->{delimiter} // "\n\n" )
            : "\n";
  
          $sync = 0 unless $self->cliopts->{sync} == -1;
      }
  }
APP_BS_PKGDEPENDS

$fatpacked{"BS.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS';
  package BS;
  role BS;
  
  use utf8;
  use v5.40;
BS

$fatpacked{"BS/Common.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_COMMON';
  use Object::Pad qw(:experimental(:all));
  
  package BS::Common;
  role BS::Common : does(BS::Path);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use IPC::Run3;
  use Tie::File;
  use Const::Fast;
  use Time::Piece;
  use Data::Dumper;
  use List::AllUtils qw(any all first);
  use Syntax::Keyword::Try;
  use Const::Fast::Exporter;
  use Syntax::Keyword::Dynamically;
  use Time::HiRes qw(gettimeofday);
  
  BEGIN {
      use Exporter;
      use parent 'Exporter';
      use vars '@EXPORT';
      use subs qw(dmsg bsx callstack __pkgfn__ const);
  
      @EXPORT = qw(dmsg bsx callstack __pkgfn__ const);
  }
  
  const our $DEBUG   => ( any { $_ } @ENV{qw(BS_DEBUG DEBUG)} ) || 0;
  const our $TRIM_RE => qr/\s*(.+)\s*\n*/i;
  
  eval {
      use Devel::StackTrace::WithLexicals;
      use PadWalker qw(peek_my peek_our);
      use Module::Metadata;
  } if $DEBUG;
  
  my class BsxRes {
      use utf8;
      use v5.40;
  
      use subs qw(dmsg);
  
      field $debug = $BS::Common::DEBUG;
  
      field @out;
      field @err;
  
      field $cmd : param     : reader;
      field $inh : param(in) : reader = \undef;
      field $outh : param(out) : mutator(out) //= \@out;
      field $errh : param(err) : reader //= \@err;
      field $dest   : param : reader = \@out;
      field $status : param : reader = 0;
  
      ADJUST {
          BS::Common::dmsg { self => $self }
      }
  };
  
  field $debug : mutator : param : inheritable = $DEBUG;
  
  APPLY($mop) {
      use utf8;
      use v5.40;
  
      use Object::Pad ':experimental(:all)';
      use Const::Fast::Exporter;
      use parent 'Exporter';
  
      use subs qw(dmsg bsx callstack __pkgfn__ const);
      our @EXPORT = qw(dmsg bsx callstack __pkgfn__ const);
  }
  
  ADJUST {
      use utf8;
      use v5.40;
      $ENV{DEBUG} = $debug = $BS::Common::DEBUG
  };
  
  method __pkgfn__ : common ($pkgname = undef) {
      $pkgname //= $class;
      "$pkgname.pm" =~ s/::/\//rg;
  }
  
  method callstack : common {
      my @callstack;
      my $i = 0;
  
      while ( my @caller = caller $i ) {
          {
              no strict 'refs';
              push @caller, \%{"$caller[0]\::"};
              push @caller, $caller[0]->META() if ${"$caller[0]\::"}{META}
          }
  
          push @callstack, \@caller;
      }
      continue { $i++ }
  
      @callstack;
  }
  
  method alldef : common (@items) {
      all { $_ } @items;
  }
  
  sub dmsg (@msgs) {
      my $self =    # Maybe there's a reason to make an anon class here?
        blessed $msgs[0] && $msgs[0]->DOES('BS::Common') ? shift @msgs : undef;
  
      if ( state $debug = ( $DEBUG || $ENV{DEBUG} // undef ) ) {
  
          my @caller = caller 0;
  
          my $out = "*** " . localtime->datetime . " - DEBUG MESSAGE ***\n\n";
  
          {
              local $Data::Dumper::Pad    = "  ";
              local $Data::Dumper::Indent = 1;
  
              $out .=
                  scalar @msgs > 1 ? Dumper(@msgs)
                : ref $msgs[0]     ? Dumper(@msgs)
                :   eval { my $s = $msgs[0] // 'undef'; "  $s\n" };
  
              $out .= "\n"
          }
  
          $out .=
            $ENV{DEBUG} && $ENV{DEBUG} == 2
            ? join "\n",
            map { ( my $line = $_ ) =~ s/^\t/  /; "  $line" } split /\R/,
            Devel::StackTrace::WithLexicals->new(
              indent      => 1,
              skip_frames => 1
            )->as_string
            : "at $caller[1]:$caller[2]";
  
          say STDERR "$out\n";
          $out;
      }
  }
  
  method ts : common ($sep = '') {
      join $sep, gettimeofday;
  }
  
  method bsx : common ($cmd_aref, %args) {
      %args = ( in => undef, out => [], err => '' ) unless scalar keys %args;
  
      dmsg { cmd => $cmd_aref, args => \%args };
  
      run3( $cmd_aref,
          map { ref $_ ? $_ : defined $_ ? \$_ : undef } @args{qw(in out err)} );
  
      my $res = BsxResult->new(
          cmd    => $cmd_aref,
          status => $?,
          %args{qw(in out err dest)}
      );
  
      #my %ret = map { $_ => $res->$_ } $args{fields}->@*;
      #   scalar %ret ? \%ret : $res;
      $res;
  }
  
  method open_as_href : common ($in, %args) {
      my ( $as_aref, $as_path );
  
      # Is it 'out' or 'dest'?
      #my $as_href = delete $args{dest} // {};
      my $as_href = first { delete $args{$_} } qw(dest out);
  
      $as_aref = $class->tie_file( $in, dest => $as_href, %args );
  
      foreach my $line (@$as_aref) {
          $line =~ s/$TRIM_RE/$1/;
  
          my ( $key, $val ) =
            $args{parse_line}->( $line, dest => $as_href, %args );
  
          next unless $key && $val;
  
          if ( $$as_href{$key} ) {
              if (   $args{no_dupes}
                  && $args{dest}->{$key}
                  && $$as_href{$key} eq $args{dest}->{$key} )
              {
                  next;
              }
  
              $$as_href{$key} = [ $$as_href{$key} ]
                if ref $$as_href{$key} ne 'ARRAY';
              push $$as_href{$key}->@*, $val;
          }
          else {
              $$as_href{$key} = $val;
          }
      }
  
      dmsg $as_href;
      $as_href;
  }
  
  method tie_file : common ($in, %args) {
      my $as_aref = [];
      my $as_href = $args{dest} // {};
  
      if ( $in isa Path::Tiny ) {
          tie @$as_aref, 'Tie::File', "$in";
      }
      elsif ( ref $in eq 'GLOB' ) {
          tie @$as_aref, 'Tie::File', $in;
      }
      elsif ( ref $in eq 'ARRAY' ) {
  
          #$as_aref = $in
          return $in;
      }
      elsif ( !ref $in ) {
          if ( -e "$in" ) {
              my $as_path = path($in);
              tie @$as_aref, 'Tie::File', "$in";
          }
          elsif ( $args{out} ) {
              @$as_aref = split /\n/, $in;
              tie @$as_aref, 'Tie::File', $args{out} if $args{out};
              ...;
          }
      }
  
      $as_aref;
  }
BS_COMMON

$fatpacked{"BS/Ext.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT';
  use Object::Pad ':experimental(:all)';
  
  package BS::Ext;
  
  role BS::Ext : does(BS::Common);
  
  use utf8;
  use v5.40;
  
  method $parse_line : common : required;
  
  method $filter_output : common : required;
BS_EXT

$fatpacked{"BS/Ext/User.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_USER';
  use Object::Pad ':experimental(:all)';
  
  package BS::Ext::User 0.01;
  role BS::Ext::User : does(BS::Common);
  
  use utf8;
  use v5.40;
  
  use Const::Fast;
  use Syntax::Keyword::MultiSub;
  
  field $parse_line : mutator : inheritable;
  field $filter_output : mutator : inheritable;
  
  #method $parse_line : common ($line, %opts) {
  #    ...;
  #};
  
  #method $filter_output : common {
  #    ...;
  #};
  
  #multi sub is_locked ($pacman_dir = "") {
  #  BS::Ext::pacman->sync
  #}
BS_EXT_USER

$fatpacked{"BS/Ext/expac.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_EXPAC';
  use Object::Pad ':experimental(:all)';
  
  package BS::Ext::expac;
  role BS::Ext::expac : does(BS::Common);
  
  use utf8;
  use v5.40;
  
  use Const::Fast;
  use Const::Fast::Exporter;
  
  const our $split_comma_re => qr/,/;
  const our %DB             => ( 'local' => 'Q', sync => 'S' );
  
  method $parse_line : common ( $line, %opts ) {
      my @fields = $opts{fields}->@*;
      map { shift @fields => $_ } split $split_comma_re, $line;
  }
  
  method $out : common ($line, %opts) {
      chomp $line;
      my %res = $class->$parse_line( $line, %opts );
      BS::Common::dmsg { line => $line, res => \%res, opts => \%opts };
      push $opts{dest}->@*, \%res;
  }
  
  method search : common ( $search, %opts ) {
      $opts{fields} //= [qw(base name)];
      $opts{dest}   //= [];
  
      $opts{find} and $opts{find} = 's';
  
      #$opts{find} = 's' if $opts{find};
  
      dmsg(
          {
              and        => eval { $opts{find} and $opts{find} = 's' },
              postfix_if => eval { $opts{find} = 's' if $opts{find} }
          }
      );
  
      const my %fields => (
          base                 => '%e',
          arch                 => '%a',
          backup_files         => '%B',
          build_date           => '%b',
          conflicts_nover      => '%C',
          depends_on           => '%D',
          description          => '%d',
          depends_on_nover     => '%E',
          optional_deps        => '%O',
          optional_deps_nodesc => '%o',
          filename             => '%f',
          signature            => '%g',
          groups               => '%G',
          conflicts_with       => '%H',
          md5sum               => '%s',
          sha256sum            => '%h',
          download_size        => '%k',
          licences             => '%L',
          install_size         => '%m',
          name                 => '%n',
          required_by          => '%N',
          version              => '%v',
          url                  => '%u',
          replaces             => '%T',
          replace_nover        => '%R',
          provides_nover       => '%S',
          provides             => '%P',
          packager             => '%p',
          package_valid_method => '%V',
          'literal_%'          => '%%',
      );
  
      my $fmtstr = $opts{fmt} // join ',', @fields{ $opts{fields}->@* };
  
      my $res = BS::Common->bsx(
          [
              'expac', "$opts{db}$opts{find}",
              $fmtstr, ( $search isa 'ARRAY' ? @$search : $search )
          ],
          out => sub ( $line, %_opts ) {
              $class->$out( $line, %opts, %_opts, fmtstr => $fmtstr );
          },
          %opts
      );
  
      dmsg( { res => $res } );
  
      $res;
  }
BS_EXT_EXPAC

$fatpacked{"BS/Ext/pacconf.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_PACCONF';
  
BS_EXT_PACCONF

$fatpacked{"BS/Ext/pacinfo.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_PACINFO';
  use Object::Pad qw':experimental(:all)';
  
  package BS::Ext::pacinfo;
  role BS::Ext::pacinfo : does(BS::Package::Meta);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use List::Util 'any';
  use Const::Fast;
  use Data::Dumper;
  
  const our $DEBUG      => any { $_ } @ENV{qw(PKGBASE_DEBUG BS_DEBUG DEBUG)} || 0;
  const our @VALID_KEYS => qw(Name Base Repository);
  const our $VALID_KEY_RE => map { qr/^($_)$/i } join '|', (@VALID_KEYS);
  const our $DEPKEY_RE    => qr/^(Requires|Optional Deps)$/i;
  
  method info : common ($pkgstr, %args) {
      my ( @out, $err );
      my $res = BS::Common->bsx(
          [ 'pacinfo', $pkgstr ],
          out => \@out,
          in  => undef,
          err => \$err
      );
  
      die "$err"   if $err;
      die "$?: $!" if $res->cmdexit->[0] != 0;
  
      my %info = ();
  
      $res = $class->to_href( \@out, %args, dest => \%info );
  
      #warn Dumper $pkgstr, \%info, \%args, $res, $err if $DEBUG;
  
      \%info;
  }
  
  method pkgbase : common ($pkgstr, %args) {
      my $info = $class->info( $pkgstr, %args );
  
      #warn Dumper($info) if $ENV{DEBUG};
      ref $$info{base} eq 'ARRAY' ? $info->{base}[0] : $$info{base};
  }
  
  method to_href : common ($in, %args) {
      my $res = BS::Common->open_as_href(
          $in, %args,
          parse_line => sub ( $line, %args ) {
              my @parsed = $class->parse_line( $line, %args );
              warn Dumper( \@parsed ) if $DEBUG;
          }
      );
  
      #warn Dumper($res) if $DEBUG;
  
      $res;
  }
  
  method parse_line : common ($line, %args) {
      my ( $key, $value ) = map {
          $_ =~ s/$BS::Common::TRIM_RE/$1/;
          $_
      } ( split /:/, $line, 1 );
  
      $key = lc($key);
  
      $value = BS::Package::Meta->parse_dep( $value, %args )
        if ( $args{resolve_deps} // 1 ) && $key =~ $DEPKEY_RE;
  
      return undef unless $key && $value;
  
      my %debug = ( key => $key, val => $value );
  
      warn Dumper( \%debug ) if $DEBUG;
  
      $key, $value;
  }
BS_EXT_PACINFO

$fatpacked{"BS/Ext/pacman.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_PACMAN';
  use Object::Pad;
  
  package BS::Ext::pacman;
  role BS::Ext::pacman : does(BS::Common) : does(BS::Ext)
    : does(BS::Package::Meta);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use BS::Common;
  use Const::Fast;
  use Data::Printer;
  use BS::Package::Meta;
  use List::Util 'any';
  
  const our %DBPATTERN_MAP => qw(package p(?:ac)?ka?ge? file file);
  const our $VALIDDB_RE => map { qr /^($_)$/i }
    ( join '|', values %DBPATTERN_MAP );
  
  field $sync;
  
  method $parse_line : common ( $line, %opts ) {
      const my $REPOPKG_STR_RE =>
        qr/(^[^\/]+)?\/($BS::Package::Meta::VALID_PKG_RE_NB[^\n])$/;
  
      chomp $line;
      my ( $repo, $pkgstr ) = $line =~ $REPOPKG_STR_RE;
  
      #BS::Common::dmsg { line => $line, repo => $repo, pkgstr => $pkgstr };
  
      my %ret = ( pkgstr => $pkgstr );
      $ret{repo} = $repo if any { $_ eq 'repo' } $opts{fields}->@*;
  
      #BS::Common::dmsg \%ret;
  
      %ret;
  };
  
  method $filter_output : common ($line, %opts) {
      if ( my %fields = ( $class->$parse_line( $line, %opts ) ) ) {
  
          #BS::Common::dmsg \%fields;
          return \%fields;
      }
  
      undef;
  };
  
  method db_valid : common (@list) {
      grep { $VALIDDB_RE } @list;
  }
  
  method sync : common (%args) {
      my @db_enabled = $class->db_valid(
          ref $args{database} eq 'ARRAY'
          ? $args{database}->@*
          : $args{database}
      );
  
      my $now = time;
      state $sync = $now;
  
      $args{res}  //= {};
      $args{dest} //= [];
      $args{now}  //= time;
  
      my ( @query_opts, %res );
  
      if ( $args{sync} || ( $args{last_sync} && $args{now} == $args{last_sync} ) )
      {
          push @query_opts, qw(-y -y);
      }
  
      $res{package} =
        BS::Common->bsx( [ qw(sudo pacman -Su), @query_opts ], %args )
        if $args{package};
  
      $res{file} = BS::Common->bsx( [ qw(sudo pacman -F), @query_opts ], %args )
        if $args{file};
  
      %res->(qw(package file));
  }
  
  method file_query : common ($filestr, %args) {
      my $now = time;
      state $sync = $now;
      $class->query(
          $filestr,
          query_opts => ['-Fq'],
          now        => $now
          ,
          %args, last_sync => $sync
      );
  }
  
  method pkg_query : common ($pkgstr, %args) {
      my $now = time;
      state $sync = $now;
      $class->query(
          $pkgstr,
          query_opts => ['-Sqs'],
          now        => $now
          ,
          %args, last_sync => $sync
      );
  }
  
  method list_db_packages : common (%args) {
      BS::Common::bsx(
          [qw(sudo pacman -Qqn)],
          in  => \undef,
          out => sub {
              state @dest = $args{dest} // [];
              $class->$parse_line(@_);
          }
      );
  }
  
  method filter_foreign_unresolvable : common ($pkg_aref, %args) {
  }
  
  method query : common ($str, %args) {
      $args{dest} //= [];
      $args{now}  //= time;
  
      BS::Common::dmsg { str => $str, args => \%args };
  
      const my $pacman_query_outh => sub ( $line, @opts ) {
  
          #BS::Common::dmsg { line => $line, opts => \@opts };
  
          if ( my ( $repo, $pkgname ) =
              $class->$filter_output( $line, %args )->@{qw(repo pkgstr)} )
          {
              push $args{dest}->@*, { repo => $repo, pkgname => $pkgname };
          }
      };
  
      if ( $args{sync} || ( $args{last_sync} && $args{now} == $args{last_sync} ) )
      {
          push $args{query_opts}->@*, qw(-y -y);
      }
  
      my $res = BS::Common->bsx(
          [ qw(sudo pacman), $args{query_opts}->@*, $str ],
          %args,
          in  => undef,
          out => $pacman_query_outh
      );
  
      $res;
  }
  
  const our @default_repo => qw(core extra multilib);
  
  const our $default_repo_str => join '\n\n',
    map {
      <<'...';
  [$_]
  SigLevel          = Required DatabaseOptional
  LocalFileSigLevel = Optional
  ...
    } @default_repo;
  
  const our $pacman_conf_default => <<'...'
  [options]
  ParallelDownloads = 10
  #DownloadUser = bs
  SigLevel    = Required DatabaseOptional
  LocalFileSigLevel = Optional
  ...
    . $default_repo_str
BS_EXT_PACMAN

$fatpacked{"BS/Ext/pacsift.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_PACSIFT';
  use Object::Pad;
  
  package BS::Ext::pacsift;
  role BS::Ext::pacsift : does(BS::Package::Meta);
  
  use utf8;
  use v5.40;
  
  method $parse_line : common ($line, %opts) {};
  
  method $out : common ($line, %opts) {};
  
  method provides : common ($pkgstr, %opts) {
      my $out = $opts{out} //= [];
      my $res = BS::Common->bsx(
          [ qw(pacsift), $opts{args}->@*, '--provides', '<&-' ],
          in   => undef,
          dest => $out,
          out  => sub { $class->$out(@_) }
      );
  }
  
  method owns_file : common ($pkgstr, %opts) {
      my $out = $opts{out} //= [];
      my $res = BS::Common->bsx(
          [ qw(pacsift), $opts{args}->@*, 'owns_file', '<&-' ],
          in   => undef,
          dest => $out,
          out  => sub { $class->$out(@_) }
      );
  }
BS_EXT_PACSIFT

$fatpacked{"BS/Ext/pactree.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_EXT_PACTREE';
  use Object::Pad;
  
  package BS::Ext::pactree;
  role BS::Ext::pactree
    : does(BS::Package::Meta)
    : does(BS::Common)
    : does(BS::Ext);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use List::Util 'uniq';
  
  method list_deps : common ($pkgstr, %args) {
      BS::Common::dmsg( { pkgstr => $pkgstr, args => \%args } );
  
      use constant DEFORDER_RE => qr/^asc.*/i;
  
      state $altorder =
        ( $args{default_order} // 'asc' ) =~ DEFORDER_RE ? 'desc' : 'asc';
  
      state $altorder_re = qr/^($altorder|r).*/i;
  
      my @deps;
  
      my @out = $class->tree(
          $pkgstr,
          linear   => 1,
          unique   => 1,
          sync     => 1,
          optional => 1,
          sync     => delete $args{sync},
          %args
      )->@*;
  
      foreach my $line (@out) {
          my $depargs = BS::Package::Meta->parse_dep( $line, %args );
          my $depid   = $$depargs{base} // $$depargs{name};
  
          push @deps, $depid
            unless $depid eq $pkgstr;
      }
  
      dmsg( { deps => \@deps } );
  
      @deps = $args{unique} ? reverse uniq reverse @deps : @deps;
  
      @deps =
        ( $args{order} !~ $altorder_re )
        ? @deps
        : reverse @deps;
  
      join $args{sep} // ' ', @deps;
  }
  
  method tree : common ($pkgstr, %args) {
      dmsg( { args => \%args } );
      my ( @flagsargs, @intsargs, @out, $in, $err );
      $args{optional} //= 1;
  
      foreach my ( $key, $value ) ( %args{qw(sync unique linear)} ) {
          push @flagsargs, substr $key, 0, 1 if $value;
      }
  
      foreach my ( $key, $value ) ( %args{qw(depth optional)} ) {
          push @intsargs, '-' . substr( $key, 0, 1 ) . $value if $value;
      }
  
      my $res = BS::Common->bsx(
          [ 'pactree', ( '-' . join '', @flagsargs ), @intsargs, $pkgstr ], %args,
          out => \@out,
          in  => undef,
          err => \$err
      );
  
      die "$err"   if $err;
      die "$?: $!" if $res->cmdexit->[0] != 0;
  
      dmsg( { out => \@out } );
  
      \@out;
  }
BS_EXT_PACTREE

$fatpacked{"BS/GPG.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_GPG';
  use Object::Pad ':experimental(:all)';
  
  package BS::GPG;
  
  class BS::GPG : does(BS::Common);
  
  use v5.40;
  
  use parent 'Exporter';
  
  use IPC::Run3;
  use BS::Common 'dmsg';
  
  sub can_sign ( $gpgiden, %opts ) {
      my @out = ();
  
      my $ret = run3(
          [ qw(gpg --verbose -a --export), $gpgiden ],
          \undef,
          sub ($line) {
              chomp $line, say $line;
              push @out, $line;
          },
          sub ($line) {
              chomp $line;
              say $line;
          }
      );
  
      1 if scalar @out;
  }
BS_GPG

$fatpacked{"BS/Package.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_PACKAGE';
  use Object::Pad qw(:experimental(:all));
  
  package BS::Package;
  
  class BS::Package : does(BS::Package::Meta);
  
  use utf8;
  use v5.40;
  
  use Carp;
  use List::Util 'any';
  use File::chdir;
  use File::Temp;
  use Const::Fast;
  
  role BS::Package::Stub : does(BS::Package::Meta) {
      field $search : inheritable : param : accessor = "";
  
      method upgrade ( $field_href, %opts ) {
          ...;
      }
  };
  
  ADJUSTPARAMS($params) {
  
      # if ( $search && none( @$name, $base ) ) {
      #     ( $base, $name ) = $self->$search()->@[qw(name base)];
      # }
  }
  
  # method $search ( $pkgstr = $search, %opts ) {
  
  # }
  
  method search : common ($search) {
      my $self = BS::Package->new( search => $search );
      $self->$search();
  
      #$self->p
  }
  
  method parse_pkgstr : common ($pkgstr) {
      const my $pkgstr_name_ptn => qr'[a-zA-Z0-9\@_\+]{1}[a-zA-Z0-9\@_\+\.\-]+';
  
      const my $pkgstr_name_re => qr/
          ^(lib\:)?
          ($pkgstr_name_ptn(\.so(?:\.[0-9\]+)?)
          |$pkgstr_name_ptn)
        /x;
  
      const my $pkgver_forbidden => quotemeta(':/-') . '\s';
  
      const my $pkgver_re => qr'
        (\=|[\<\>](?:\=)?)
        ([^$pkgver_forbidden]+)
      'x;
      const my $optdep_re => qr/(:(:)\s+(.+))/;
  
      const my $pkgstr_re => qr/
          $pkgstr_name_re #
          (?:$pkgver_re)?
          $optdep_re
        /x;
  
      # Not working...
      #const my $_pkgstr_re => qr/$pkgstr_re_str/;
  
      #:wqwarn np nojoin => $pkgstr_re join => $_pkgstr_re if $DEBUG;
  
      my ( $prefix, $_pkgstr, $isfile, $sep, $attr, @extra ) =
        $pkgstr =~ $pkgstr_re;
  
      dmsg( { $prefix, $_pkgstr, $isfile, $sep, $attr, @extra } );
  }
  
  method lookup : common ($field_href, %opts) {
      my $stub = BS::Package::Stub->new(%$field_href);
  
      if ( $stub->is_file ) {
  
      }
      else {
          # TODO: More constraints
          if ( $stub->version ) {
  
          }
      }
  
  }
  
  method updchecksums : common {
      $class->bsx( ['updchecksums'] );
  }
  
  method writesrcinfo : common ($out, @makepkg_args) {
      $class->printsrcinfo( $out, @makepkg_args )->out;
  }
  
  method printsrcinfo : common ($out, @makepkg_args) {
      $class->bsx(
          [ 'makepkg', '--printsrcinfo', @makepkg_args ],
          out => ( ref $out eq 'ARRAY' ? $out : \$out )
      );
  }
  
  method fetch : common ($pkgstr, %args) {
      my $pkgres   = BS::Package::Meta->resolve_base($pkgstr);
      my $srccache = path( $args{srccache} // $args{dest} );
      my $workdir  = Path::Tiny->tempdir;
      my $res;
  
      if ( lc( $args{repo} ) eq 'aur' ) {
          $res = $class->bsx( [qw(git clone --bare $)] );
      }
      elsif (
          any { $args{repo}->{name} eq $_ && $args{repo}->{base_uri} }
          keys $args{repo_enabled}->%*
        )
      {
          $res = $class->bsx( [qw(git clone --bare $)] );
      }
      else {
          $res = $class->bsx(
              [ qw(pkgctl repo clone --protocol=https), $$pkgres{base} ] );
      }
  
      carp $res->out;
  
      $class->bsx(
          [
              qw(git clone), "$srccache/$$pkgres{base}",
              "$workdir/$$pkgres{base}"
          ]
      );
  
      carp $res->out;
  }
  
BS_PACKAGE

$fatpacked{"BS/Package/Manifest.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_PACKAGE_MANIFEST';
  use Object::Pad;
  
  package BS::Package::Manifest;
  class BS::Package::Manifest :isa(BS::Package);
  
  use utf8;
  use v5.40
BS_PACKAGE_MANIFEST

$fatpacked{"BS/Package/Meta.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_PACKAGE_META';
  use Object::Pad ':experimental(:all)';
  
  use utf8;
  use v5.40;
  
  package BS::Package::Meta;
  role BS::Package::Meta : does(BS::Common);
  
  field $base    : inheritable : param : accessor = "";
  field $name    : inheritable : param : accessor //= [$base];
  field $current : inheritable : accessor //= $$name[0];
  
  field $version   : inheritable : param : accessor = "";
  field $rel       : inheritable : param : accessor = "";
  field $epoch     : inheritable : param : accessor = "";
  field $sources   : inheritable : param : accessor = [];
  field $checksums : inheritable : param : accessor = [];
BS_PACKAGE_META

$fatpacked{"BS/Path.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_PATH';
  use Object::Pad ':experimental(:all)';
  
  package BS::Path;
  
  role BS::Path;
  
  use utf8;
  use v5.40;
  
  class Path {
      use utf8;
      use v5.40;
  
      use BS::Common;
      use Path::Tiny;
  
      field $pathstr : param(path);
      field $_path : mutator($path);    #{ path($pathstr) };
  
      method BUILDARGS : common ($path, %opts) {
          ( path => $path, %opts );
      }
  
      ADJUSTPARAMS($params) {
  
          $_path = path($pathstr);
          BS::Common::dmsg(
              {
                  self     => $self,
                  params   => $params,
                  caller_0 => [ caller 0 ]
              }
          );
      };
  
      method exists {
          $_path->exists;
      }
  
      method basename (@suffixes) {
          push @suffixes, $ENV{PKGEXT}
            unless scalar @suffixes;
  
          $_path->basename(@suffixes);
      }
  
      method if_exists {
          $self->exists ? $_path : undef;
      }
  };
  
  method path : common ($path) { Path->new($path) }
  
  method if_exists : common ($path) {
      my $bspath = $class->path($path);
      ( $bspath->exists ? $bspath : undef );
  }
BS_PATH

$fatpacked{"BS/Repo.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_REPO';
  
BS_REPO

$fatpacked{"BS/Repo/User.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_REPO_USER';
  
BS_REPO_USER

$fatpacked{"BS/alpm.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'BS_ALPM';
  use Object::Pad ':experimental(:all)';
  
  package BS::alpm;
  role BS::alpm : does(BS::Common);
  
  use utf8;
  use v5.40;
  
  use Inline C               => config => enable => autowrap => myextlib =>
    '/usr/lib/libalpm.so.15' => libs   =>
    '-lalpm -lalpm_list -lalpm_depends -lalpm_packages';
  
  ##use Inline C => "alpm_initialize();";
  
  #APPLY {
  #    alpm_initialize();
  #    BS::alpm::alpm_initialize();
  #}
  
  method print_self {
  
      #say BS::alpm::alpm_initialize();
      #say Dumper($self);
      warn BS::Common::dmsg( { self => $self } );
  }
BS_ALPM

$fatpacked{"Minilla/ModuleMaker/InlineMakeMaker.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'MINILLA_MODULEMAKER_INLINEMAKEMAKER';
  package Minilla::ModuleMaker::InlineMakeMaker;
  use strict;
  use warnings;
  use utf8;
  use Data::Section::Simple qw(get_data_section);
  use Text::MicroTemplate qw(render_mt);
  use Data::Dumper;
  use File::Spec::Functions qw(catdir rel2abs);
  use File::Find ();
  use TAP::Harness::Env;
  use Cwd;
  
  # This module is EXPERIMENTAL.
  # You can use this. But I may change the behaviour...
  use Moo;
  no Moo;
  use Minilla::Util qw(spew_raw);
  sub generate {
      my ($self, $project) = @_;
      local $Data::Dumper::Terse = 1;
      local $Data::Dumper::Useqq = 1;
      local $Data::Dumper::Purity = 1;
      local $Data::Dumper::Indent = 1;
      local $Data::Dumper::Sortkeys = 1;
      my $content = get_data_section('Makefile.PL');
      my $mt = Text::MicroTemplate->new(template => $content, escape_func => sub { $_[0] });
      my $src = $mt->build->($project);
      spew_raw('Makefile.PL', $src);
  }
  sub prereqs {
      my ($self, $project) = @_;
      my %configure_requires = (
          'Inline::MakeMaker' => '0.86', 
          'ExtUtils::MakeMaker' => $self->_eumm_minimum_version($project),
      );
      my $prereqs = +{
          configure => {
              requires => {
                  %configure_requires,
              }
          }
      };
      for my $key (qw(tap_harness_args use_xsutil c_source allow_pureperl requires_external_bin)) {
          if( $project->$key ){
              die "$key does not supported by " . __PACKAGE__;
          }
      }
      return $prereqs;
  }
  sub _eumm_minimum_version {
      my ($self, $project) = @_;
      if (@{ $project->unsupported->os }) {
          return '7.26'; # os_unsupported
      }
      return '6.64'; # TEST_REQUIRES (and MYMETA)
  }
  sub run_tests {
      my $harness = TAP::Harness::Env->create({
          verbosity => 0,
          lib       => [ map { rel2abs(catdir(qw/blib/, $_), cwd) } qw/arch lib/ ],
          color     => -t STDOUT
      });
      my @tests = sort +_find(qr/\.t$/, 't');
      if ($ENV{RELEASE_TESTING}) {
          push @tests, sort +_find(qr/\.t$/, 'xt');
      }
      $harness->runtests(@tests)->has_errors and die;
  }
  sub _find {
      my ($pattern, $dir) = @_;
      my @ret;
      File::Find::find(sub { push @ret, $File::Find::name if /$pattern/ && -f }, $dir) if -d $dir;
      return @ret;
  }
  1;
  __DATA__
  @@ Makefile.PL
  ? my $project = shift;
  ? use Data::Dumper;
  # =========================================================================
  # THIS FILE IS AUTOMATICALLY GENERATED BY MINILLA.
  # DO NOT EDIT DIRECTLY.
  # =========================================================================
  use 5.006;
  use strict;
  
  use Inline::MakeMaker;
  use ExtUtils::MakeMaker <?= $project->module_maker->_eumm_minimum_version($project) ?>;
  ? if ( @{ $project->unsupported->os } ) {
  ?   for my $os ( @{ $project->unsupported->os } ) {
  os_unsupported if $^O eq <?= B::perlstring($os) ?>;
  ?   }
  ? }
  ? if ( @{ $project->requires_external_bin || [] } ) {
  use Devel::CheckBin;
  ?   for my $bin ( @{ $project->requires_external_bin } ) {
  check_bin('<?= $bin ?>');
  ?   }
  ? }
  ? my $prereqs = $project->cpan_meta->effective_prereqs;
  ? my $d = sub { Dumper($prereqs->merged_requirements([$_[0]], ['requires'])->as_string_hash) };
  my %WriteMakefileArgs = (
      NAME     => '<?= $project->name ?>',
      DISTNAME => '<?= $project->dist_name ?>',
      VERSION  => '<?= $project->version ?>',
      EXE_FILES => [<?= $project->script_files ?>],
      CONFIGURE_REQUIRES => <?= $d->('configure') ?>,
      BUILD_REQUIRES     => <?= $d->('build') ?>,
      TEST_REQUIRES      => <?= $d->('test') ?>,
      PREREQ_PM          => <?= $d->('runtime') ?>,
  );
  WriteMakefile(%WriteMakefileArgs);
MINILLA_MODULEMAKER_INLINEMAKEMAKER

s/^  //mg for values %fatpacked;

my $class = 'FatPacked::'.(0+\%fatpacked);
no strict 'refs';
*{"${class}::files"} = sub { keys %{$_[0]} };

if ($] < 5.008) {
  *{"${class}::INC"} = sub {
    if (my $fat = $_[0]{$_[1]}) {
      my $pos = 0;
      my $last = length $fat;
      return (sub {
        return 0 if $pos == $last;
        my $next = (1 + index $fat, "\n", $pos) || $last;
        $_ .= substr $fat, $pos, $next - $pos;
        $pos = $next;
        return 1;
      });
    }
  };
}

else {
  *{"${class}::INC"} = sub {
    if (my $fat = $_[0]{$_[1]}) {
      open my $fh, '<', \$fat
        or die "FatPacker error loading $_[1] (could be a perl installation issue?)";
      return $fh;
    }
    return;
  };
}

unshift @INC, bless \%fatpacked, $class;
  } # END OF FATPACK CODE

use Object::Pad ':experimental(:all)';

package App::BS::CLI::pacman;

class App::BS::CLI::pacman : does(BS::Common);

use utf8;
use v5.40;

use lib 'lib';

use IPC::Run3;
use Const::Fast;
use Syntax::Keyword::Try;
use Syntax::Keyword::Dynamically;

use BS::Common 'dmsg';

const our $S_IPCRUN3_FATAL =>
"!! ERROR: $0 ran into An unknown fatal error has while attempting to execute your system's pacman binary. Your system may be experiencing instability at the moment. Consider booting from a live image and clearing up the issue before running $0 again.";

field $cliopts : param(dest) = { verbose => 1 };
field $env : param : reader = { %ENV{qw'as_needed debug verbose'} };

field $status : reader;
field $errmsg : reader;
field $out_aref = [];
field $err_aref = [];

method $run (%opts) {

    # Why am I using Syntax::Keyword::Dynamically over local outside of suppport
    # for Ojbect::Pad?
    dynamically $status   = 0;
    dynamically $errmsg   = "";
    dynamically $out_aref = [];

    my @overwrite = $ARGV[0] eq '-S' ? qw(--overwrite '*' --noconfirm) : ();
    push @overwrite, '--needed' if $$env{as_needed};

    try {
        my $ret = run3(
            [ 'pacman', @overwrite, '--verbose', @ARGV ],
            $opts{stdin} // undef,
            sub ($line) {
                chomp $line;
                say $line;
                push @$out_aref, $line;
            },
            sub ($line) {
                chomp $line;
                say STDERR $line;
                push @$err_aref, $line;
            }
        );

        ( $status, $errmsg ) =
          $? != 0 ? ( $?, $! ) : ( 0, '', $$err_aref[ scalar @$err_aref ] );

        BS::Common::dmsg(
            {
                overwrite => \@overwrite,
                ret       => $ret,
                errmsg    => $errmsg,
                status    => $status,
                opts      => \%opts
            }
        )
    }
    catch ($e) {
        die $S_IPCRUN3_FATAL;
    }
    finally {
        chomp $errmsg;
        $errmsg =~ s/^(.+)[\s\r\n]*/$1/g;

        BS::Common::dmsg(
            { errmsg => $errmsg, status => $status, opts => \%opts } )
    };

    $status ? 0 : 1;
}

method run : common ($argv, %opts) {
    my $app  = $class->new( argv => $argv, %opts{qw''} );
    my $exit = $app->$run;
    $app;
}

package main;

use v5.40;

use BS::Common 'dmsg';

sub run {
    our $app = App::BS::CLI::pacman->run( \@ARGV );
    BS::Common::dmsg( { app => $app } );
}

run
