#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package srv;

class srv : does(Frame);

use utf8;
use v5.40;

# our $app = sub {
#     use Data::Dumper;

#     #use Plack::Builder;
#     use Plack::App::Directory;

#     warn Dumper(@_);

#     #return [ 200
#     #  , [[ 'Content-Type' => 'application/json' ]]
#     #  , encode_json({ hello => "world" })]

#     Plack::App::Directory->new( { root => $_[0] // "$ENV{BS_ROOT}/repo" } )
#       ->to_app;
# };

method startup {
  my $r = $self->routes;
}

unless (caller) {
    require Plack::Runner;

    my $runner = Plack::Runner->new;
    $runner->parse_options( qw(-s Frame::Server), @ARGV );
    $runner->run( init->to_app );

    exit( $? // 0 );
}

$app
