#!/usr/bin/env bash
shopt -s nullglob
[[ "${BS_DEBUG:-${DEBUG:-0}}" -ne 0 ]] && set -x

[[ -z "$BS_REPOROOT" ]] &&
  [[ -d "$BS_REPOROOT" ]] &&
  echo "Error BS_REPOROOT must be defined" && exit 1

[[ -z "$BS_ROOT" ]] &&
  [[ -d "$BS_REPOROOT" ]] &&
  echo "Error: BS_ROOT must be defined" && exit 1

scriptdir="${0//\/$(basename "$0")/}"
. "$scriptdir/bs-common.sh"

repo="${BS_REPO:-universe}"
repodb="$BS_REPOROOT/$repo/os/$BS_TARGET/$repo.db.tar.zst"
gpgpubid="${BS_GPGID:-${BS_GPGFPR:-${BS_GPG_PUBID:-${GPGKEYID}}}}"

rebodb() {
  echo "$BS_REPOROOT/$BS_REPO/os/$BS_TARGET/$repo.db.tar.zst"
}

signpkgs() {
  _sign_rel_flow "$@"
}

_sign_rel_flow() {
  files=("$@")
  echo "Signing ${files[*]}..."

  [[ -e "${files[*]:0:1}" ]] || files=("$pkgdest"/*.pkg.tar.zst)
  complete=()

  for f in "${files[@]}"; do
    if [[ ! -e "$f" ]]; then
      echo "Could not locate package file '$f'!! Skipping..."
    fi

    for pkg in "${complete[@]}"; do
      [[ -z "${f//$pkg/}" ]] &&
        echo "[◎] Already signed '$f'. Skipping..." &&
        continue 2
    done

    signpkg "$f"
    copy2repo "$f"
    [[ "${REPOADD_IGNOREERROR:-0}" ]] && repoadd "$f"
    err=$?

    echo ""
    complete+=("$f")
  done

  repoadd "${files[@]}"
  err=$?

  echo "${complete[@]}"
  return $err
}

signpkg() {
  f="$1"

  if [[ -f "$f.sig" ]]; then
    echo "[◎] Signature file already exists for '$f'."
    if [[ "$BS_CLOBBER" -ne 1 ]]; then
      echo "Skipping..."
    else
      rm -r "$f.sig"
      signpkg "$f"
    fi
  else
    gpg -u "$gpgpubid" -sb "$f"
    gpgerr=$?
    [[ $gpgerr -eq 0 ]] &&
      echo "[●] Signed '$f' with '$gpgpubid'"
  fi

  return "$gpgerr"
}

copy2repo() {
  f="$1"
  status=0

  if [[ -f "$repodir/$(basename "$f")" ]] && [[ "$BS_CLOBBER" -ne 1 ]]; then
    printf "[◎] Package with identical filename '%s' already exists " \
      "$(basename "$f")"
    printf "in repo '%s'. Skipping...\n" "$repodb"
  else
    cp -vaf "$f" "${f}.sig" "$repodir" 2>&1
    status=$?
    [[ $status -eq 0 ]] &&
      echo "[●] Copied '$f' to repo '$repodir'..."
  fi

  return $status
}

repoadd() {
  perl ${DEBUG:+-d:Trace} -MIPC::Run3 -e 'use v5.40; use BS::GPG; my $gpgid = shift @ARGV; my $repodb = shift @ARGV; my @args = qw(psv); push @args, "n" if $ENV{BS_CLOBBER}; my @gpgid = $gpgid && BS::GPG::can_sign($gpgid) ? ("-k", $gpgid) : (); my $ret = run3([ qw(repo-add --include-sigs), @gpgid, "-" . (join "", @args), $repodb, @ARGV ]);' "$gpgpubid" "$repodb" "$@"

  repoaddexit=$?
  if [[ $repoaddexit -eq 0 ]]; then
    echo "[●] \`repo-add -nps... '$repodb' '$f'\` exited successfully!"
  else
    >&2 echo "[✖︎] \`repo-add -nps... '$repodb' '$f'\` failed with '$repoaddexit'!"
  fi

  return $repoaddexit
}
