#!/usr/bin/env bash

shopt -s nullglob
[ ${BS_DEBUG:-0} -ne 0 ] && set -x;

scriptdir="${0//\/$(basename "$0")}"
repodir="$BS_REPO"
repodb="${BS_REPO}/universe.db.tar.zst"

signpkgs() {
  _sign_rel_flow "$@"
}

_sign_rel_flow() {
  files=("$@")
  [[ -f "${files[*]:0:1}" ]] || files=("$PKGDEST"/*.pkg.tar.zst)
  complete=()

  for f in "$PKGDEST"/*.pkg.tar.zst; do
    for pkg in "${complete[@]}"; do
      [[ -z "${f//$pkg}" ]] && echo "[◎] Already signed '$f'. Skipping..." \
        && continue 2
    done

    signpkg "$f"
    copy2repo "$f"
    repoadd "$f"
    err=$?
    
    echo ""
    complete+=("$f")
  done

  echo "${complete[@]}"
  return $err
}

signpkg() {
  f="$1"

  if [[ -f "$f.sig" ]]; then
    echo "[◎] Signature file already exists for '$f'. Skipping..."
  else
    gpg -u "${BS_GPG_PUBID:-$GPGKEYID}" -sb "$f"
    gpgerr=$?
    [[ gpgerr -eq 0 ]] \
      && echo "[●] Signed '$f' with '${BS_GPG_PUBID:-$GPGKEYID}'"
  fi

  return $gpgerr
}

copy2repo() {
  f="$1"

  if [[ -f "$repodir/$(basename $f)" ]]; then
    printf "[◎] Package with identical filename '%s' already exists " \
      "$(basename "$f")"
    
    printf "in repo '%s'. Skipping...\n" "$repodb"
  else
    cp -vaf "$f" "${f}.sig" "$repodir" 2>&1
    cpstatus=$?
    [[ cpstatus -eq 0 ]] \
      && echo "[●] Copied '$f' to repo '$repodir'..."
  fi

  return $cpstatus
}

repoadd() {
  f="$1"

  repo-add -npsv --include-sigs "$repodb" \
    "$repodir/$(basename "$f")"

  repoaddexit=$?
  if [[ $repoaddexit -eq 0 ]]; then
    echo "[●] \`repo-add -nps... '$repodb' '$f'\` exited successfully!"
  else
    >&2 echo "[✖︎] \`repo-add -nps... '$repodb' '$f'\` failed with '$repoaddexit'!"
  fi

  return $repoaddexit
}

