#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package srcinfo::cli;
use lib 'lib';
class srcinfo::cli : does(BS::Common);

use utf8;
use v5.40;

use parent 'Exporter';
use vars '@EXPORT';

@EXPORT = qw(srcinfo);

use Cwd;
use Getopt::Long qw'GetOptionsFromArray :config bundling auto_abbrev';
use Path::Tiny;
use Const::Fast;
use IPC::Run3;
use BS::Src::SRCINFO;

const our %OUTFMT => (
    bash => 'srcinfo::bash'
    , # POSIX will probably be the only other in this category but I think that's basically just a .SRCINFO file without changes
    json => 'JSON::MaybeXS',
    toml => 'TOML::Tiny',
    yaml => 'YAML::Tiny'
);

field $clispec : param;
field $cliopt  : param(clidest) = {};
field $argv    : param;
field $infile = path( Cwd::abs_path(cwd) );
field $field;
field $format = { %OUTFMT{bash} };
field $srcinfo;

ADJUSTPARAMS($params) {
    my @getoptspec = ();

    foreach my ( $k, $v ) (@$clispec) {
        if ($k eq '<>' && ref $v eq 'CODE') {
           my $ogsub = $v;
           $v = sub ($barearg) {
              $ogsub->( $self, $barearg );
           };

           push @getoptspec, ($k, $v);
        }
        else {
            my $opt = "$k"; #=$v"
            $opt .= "=$v" unless $v eq 'f';
            push @getoptspec, $opt
        }
    }

    GetOptionsFromArray( $argv, $cliopt, @getoptspec );

    dmsg({ self => $self, argv => $argv, clioptspec => \@getoptspec, caller => [[caller 0],[caller 1], [caller 3]]});
} 

method run : common ($argv, $clispec, $cliopt = {} ) {
    $class->new( clispec => $clispec
      , argv => $argv
      , cliopt => $cliopt )
}

method load ($in = undef) {
    srcinfo::SRCINFO->new(file => $in)
}

package main;

use Path::Tiny;

our @clispec = (
    'field' => 's',
    'format' => 's',
    'pretty-print' => 'f',
    '<>' => sub ( $self, $barearg ) {
        my $srcinfo = $self->load( path($barearg)->assert( sub { $_->exists } ) );
        BS::Common::dmsg({ srcinfo => $srcinfo, $srcinfo->srcinfo})
    }
);

sub run {
    srcinfo::cli->run(\@ARGV ,\@clispec);
}

run()
