#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package srcinfo;
use lib 'lib';
class srcinfo : does(BS::Common);

use utf8;
use v5.40;

use parent 'Exporter';
use vars '@EXPORT';

@EXPORT = qw(srcinfo);

use Cwd;
use Getopt::Long qw'GetOptionsFromArray :config bundling auto_abbrev';
use Path::Tiny;
use Const::Fast;
use IPC::Run3;
use BS::Src::SRCINFO;

const our %OUTFMT => (
    bash => 'srcinfo::bash'
    , # POSIX will probably be the only other in this category but I think that's basically just a .SRCINFO file without changes
    json => 'JSON::MaybeXS',
    toml => 'TOML::Tiny',
    yaml => 'YAML::Tiny'
);

field $clispec : param;
field $cliopt  : param(clidest) = {};
field $argv    : param;
field $infile = path( Cwd::abs_path(cwd) );
field $field;
field $format = { %OUTFMT{bash} };
field $srcinfo;

ADJUSTPARAMS($params) {
    GetOptionsFromArray( $argv, $cliopt, @$clispec );
}

method run : common ($argv, $clispec, $cliopt = {} ) {
    $class->new( clispec => $clispec
      , argv => $argv
      , cliopt => $cliopt )
}

method load ($in = undef) {
    srcinfo::SRCINFO->new($in)
}

package main;

our @clispec = (
    'field=s',
    'format=s',
    'pretty-print',
    '<>' => sub ( $self, $barearg ) {
        #$self->load( path($barearg)->assert( sub { $_->exists } ) )
    }
);

sub run {
    srcinfo->run(\@ARGV ,\@clispec);
}

run()
