#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package srcinfo::cli;
use lib 'lib';

class srcinfo::cli : does(BS::Common);

use utf8;
use v5.40;

use parent 'Exporter';
use vars '@EXPORT';

use Cwd qw( cwd );
use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case bundling auto_abbrev);
use Path::Tiny;
use Const::Fast;
use IPC::Run3;
use List::Util qw'uniq first';
use BS::Package::SRCINFO;

const our $ENV_RE => qr/^(.*sh|env(?:vironment)?|export)$/;

const our %OUTFMT => (

    $ENV_RE => 'srcinfo::bash'
    , # POSIX will probably be the only other in this category but I think that's basically just a .SRCINFO file without changes
    json => sub ( $srcinfo, $inref, %opt ) {
        $srcinfo->as_json;
    },
    toml          => 'TOML::Tiny',
    yaml          => 'YAML::Tiny',
    storable      => '',
    'data-dumper' => ''
);

field $clispec : param;
field $cliopt  : param(clidest) : reader;
field $argv    : param;

field $infile = path( Cwd::abs_path(cwd) . '/.SRCINFO' );

# Is there somewhere we can handle a no clobber flag in the environment
# more consistently?
field $outfile { $infile unless %$cliopt{qw(readonly noop no-update)} };

field $field = $$cliopt{field};
field $format : reader = $$cliopt{format} // { %OUTFMT{$ENV_RE} };

field $srcinfo_href = {};

field $srcinfo : reader;

ADJUSTPARAMS($params) {
    if ( $$cliopt{format} ) {
        if ( $$cliopt{format} =~ $ENV_RE ) {
            $format = $OUTFMT{$ENV_RE};
        }
        elsif ( my $key = first { $format eq $_ } keys %OUTFMT ) {
            $format = $OUTFMT{$key}

            # Init serializer with settings
        }
        else {
            Bs::Common::warn("Option --format=$$cliopt{format} is not valid");
            $format = $OUTFMT{$ENV_RE};
        }
    }
}

method get_options ( $argv, $optspec, $optdest, %optss ) {
    my @getoptspec = ();

    foreach my ( $k, $v ) (@$optspec) {
        if ( $k eq '<>' && ref $v eq 'CODE' ) {
            my $ogsub = $v;
            $v = sub ($barearg) {
                $ogsub->( $self, $barearg );
            };

            push @getoptspec, ( $k, $v );
        }
        else {
            my $opt = "$k";    #=$v"
            $opt .= "=$v" unless $v eq 'f';
            push @getoptspec, $opt;
        }
    }

    GetOptionsFromArray( ( $argv // \@ARGV ), $optdest, @getoptspec );
}

# sub pkgfile_glob ( $srcinfo, $pkgver ) {
#     my $pkgver_str;

#     BS::Common::dmsg( { srcinfo => $srcinfo, pkgver => $pkgver } );

#     if ($pkgver) {
#         if (
#             my $pkgver_href =
#             ( ( $pkgver && ref $pkgver eq 'HASH' ) ? \%$pkgver : undef ) // (
#                 $pkgver eq $ENV{PKGVER_CURR}
#                 ? { $srcinfo->%{qw'epoch ver rel'} }
#                 : undef
#             )
#           )
#         {
#             $pkgver_str .= "$$pkgver_href{epoch}:" if $$pkgver_href{epoch};
#             $pkgver_str .= $$pkgver_href{ver};
#             $pkgver_str .= "-$$pkgver_href{rel}" if $$pkgver_href{rel};
#         }
#         elsif ($pkgver) {
#             $pkgver_str = $pkgver;
#         }
#     }
#     my $glob =
#       $$srcinfo{pkgname} eq 'ARRAY'
#       ? '{' . ( join ',', $$srcinfo{pkgname}->@* ) . '}-'
#       : "$$srcinfo{pkgname}"
#       . (
#         ref $$srcinfo{arch} eq 'ARRAY'
#         ? ( $pkgver_str ? " -$pkgver_str-" : "-*" ) . "-{"
#           . ( join ',', $$srcinfo{arch}->@* ) . '}'
#         : "-$$srcinfo{arch}"
#       ) . ".pkg.tar.zst";

#     $glob;
# }

method fname_wildcard_nover ( $pkgver = undef, $arch = undef )
{    # pass your own or set to 1 for current
    pkgfile_glob( $srcinfo_href, $pkgver );
}

method run : common ($argv, $clispec, $dest //= {}, %opt) {
    my $self = $class->new(
        clispec => $clispec,
        argv    => $argv,
        clidest => $dest
    );

    BS::Common::dmsg( { self => $self } );

    say $self->srcinfo->as( $self->format, $$dest{field} );
    $self;
}

method load ($in) {
    $infile  = $in;
    $srcinfo = BS::Package::SRCINFO->new( file => $in );
}

package main;

use Path::Tiny qw( path );

#         GetOptions( "library=s" => \@libfiles );
#         @libfiles = split( /,/, join( ',', @libfiles ) );
our @clispec = (
    'field|fields|out-fields|outfields|filter|select' => 's{1,}',
    'format|out-format|fmt|of|outfmt'                 => 's',
    'pretty-print!'                                   => 'f',
    '<>' => sub ( $self, $barearg ) {
        my $srcinfo =
          $self->load( path($barearg)->assert( sub { $_->exists } ) );
    }
);

our %cliopt = ( field => [] );

sub run {
    srcinfo::cli->run( \@ARGV, \@clispec, \%cliopt );
}

run()
