#!/usr/bin/env ksh

[[ ${DEBUG:-0} -ne 0 ]] && set -x -ofunctrace

function err {
  msg="$1"
  echo >&2 "❌️ $msg"
  return 0
}

function cpan2aur_sysperl {
  package="$1"
  plenv shell system
  cpan2aur "$1"
}

packagelist=("$@")
if [[ ${#packagelist[*]} -lt 1 ]]; then
  err "No package names given!"
  exit 1
fi

for package in ${packagelist[*]}; do
  [[ -z $package ]] &&
    err "'\$package'' is an empty string!" &&
    exit 1

  pkgname="${package//::/-}"
  pkgname="perl-${pkgname,,*}"

  [[ "${NOOP:-0}" -eq 1 ]] && echo "$pkgname" && continue 

  if [[ -z "$REBUILD_ALL" ]]; then
    [[ -n "$(sudo pacman -Ssq "$pkgname")" ]] &&
     [[ "$?" -eq 0 ]] &&
     >&2 echo "'$pkgname' is already in the pacman sync database" &&

    continue
  fi

  #[[ -f "$pkgname"* ]] || cpan2aur "$pkgname";

  cpan2aur_sysperl "$package" || continue

  srcdistglob_res=(./"$pkgname-"*src.tar.gz)
  srcdist="$(basename "${srcdistglob_res[*]:0:1}")"
  
  [[ ! -f "$srcdist" ]] &&
    err "Could not find source distribution in '$(pwd)'" &&
    continue

  pkgver="${srcdist##"$pkgname-"}"
  pkgver="${pkgver%%.src.tar.gz}"

  [[ -z "$pkgver" ]] &&
    err "Could not properly parse package version string from source distribution filename." &&
    continue

  srcdir="$pkgname-$pkgver"
  mkdir -pv "$srcdir" || continue

  bsdtar -xvf "$pkgname-$pkgver.src.tar.gz" -C"$srcdir" # || continue
  cd "$srcdir/$pkgname" || continue

  nvim PKGBUILD

  makepkg -Lisf
done
