#!/usr/bin/env perl

use Object::Pad ':experimental(:all)'

package gitremotesync;
class gitremotesync;

use utf8;
use v5.40;

use IPC::Nosh;
use IPC::Nosh::Common;
use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case auto_abbrev bundling long_prefix_pattern=-(?:-)?);

