#!/usr/bin/env perl
package BS::gobuild;

use utf8;
use v5.40;

use File::chdir;
use Path::Tiny;
use Data::Dumper;

use Const::Fast;
use Getopt::Long
qw(GetOptionsFromArray :config no_ignore_case auto_abbrev bundling long_prefix_pattern=--|-);
use IPC::Nosh;
use IPC::Nosh::Common;

our @out = ();
our @err = ();

my $argv = \@ARGV;

const our %CLI_GOENV_DEFAULT => (
    goos       => lc( `uname -s` =~ s/[\n\r]+//rg ),
    goarch     => lc( `uname -m` =~ s/[\n\r]+//rg =~ s/x86_64/amd64/rg ),
    gohostos   => lc( `uname -s` =~ s/[\n\r]+//rg ),
    gohostarch => lc( `uname -m` =~ s/[\n\r]+//rg =~ s/x86_64/amd64/rg ),
    goarm64    => undef,
    goarm      => undef,
    goamd64    => undef
);

const our %GOARG_DEFAULTS => (
    x          => 1,
    ldflags    => '-compressdwarf=false',
    buildmode  => 'pie',
    mod        => 'readonly',
    modcacherw => 1
);

const our $CLEAN_PREBUILD => qr'pre|prior|before|start|each|once'xxi;
const our $CLEAN_FREQ     => qr'(?::(once|every|each))?';

const our $CLEAN_POSTBUILD => qr'^(
  (?:post|after|success|fail
     $CLEAN_FREQ)
   |(?:each|every)
   |exit
  )$'xxi;

our %cliopts = ( %CLI_GOENV_DEFAULT, %GOARG_DEFAULTS, clean => ['pre'] );

GetOptionsFromArray(
    $argv,
    \%cliopts,
    ( map { "$_=s" } keys %CLI_GOENV_DEFAULT ),
    (
        map {
            ( $GOARG_DEFAULTS{$_} !~ /^(1|0)$/ || !$GOARG_DEFAULTS{$_} )
              ? "$_=s"
              : $_
          }
          keys %GOARG_DEFAULTS
    ),
    'clean=s@',
    'tidy',
    '<>' => sub ($barearg) {
        $cliopts{srcdir} = path($barearg)->assert(
            sub {
                $_->is_dir;
            }
        );
    }
);

push $cliopts{clean}->@*, map { split /,/, $_ } $cliopts{clean}->@*;

my $debug = $cliopts{debug} || $ENV{DEBUG};

foreach my ( $key, $val ) ( %cliopts{ map { lc $_ } keys %CLI_GOENV_DEFAULT } ) {

    # warn Dumper( $key, $val ) if $debug;
    dmsg $key, $val;
    $ENV{ uc $key } = $val if $val;
}

my @goarg;

foreach my ( $k, $v ) ( %cliopts{ keys %GOARG_DEFAULTS } ) {
    if ( $v =~ /^(1|0)$/ && $v == 1 ) {
        push @goarg, "-$k";
    }
    elsif ($v) {
        push @goarg, "-$k", $v;
    }
}

# say STDERR Dumper(
our $dbg_state_prebuild = {
    argv          => $argv,
    cliopts       => \%cliopts,
    goarg         => \@goarg,
    goenvironment => \%CLI_GOENV_DEFAULT,
      ENV         => { %ENV{ keys %CLI_GOENV_DEFAULT } }
};

# );

dmsg($dbg_state_prebuild);

sub clean ($aref) {
    ...;

    foreach my $val (@$aref) {
        if ( $val =~ $CLEAN_PREBUILD ) {

        }
        elsif ( my @when = ( $val =~ $CLEAN_POSTBUILD ) ) {
            if ( scalar @when == 2 ) {
                if ( $when[0] =~ $CLEAN_FREQ ) {

                }
            }
        }
    }
}

sub build {
    $CWD = $cliopts{srcdir};
    our $run = run( [ qw(go install), @goarg ] );
    dmsg($run);
    $run;
}

sub dist {
    my $goarch = $cliopts{goarch};

    my $goarch_ext =
        $goarch eq 'amd64' ? $cliopts{goamd64}
      : $goarch eq 'arm64' ? $cliopts{goarm64}
      :                      undef;

    my $distdir = "";
}

our $run = build();
dmsg $run

  #exit $run->status;
