#!/usr/bin/env perl
package BS::gobuild;

use utf8;
use v5.40;

use File::chdir;
use Path::Tiny;
use Data::Dumper;
use IPC::Run3;
use Const::Fast;
use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case auto_abbrev bundling long_prefix_pattern=-(?:-)?);
use IPC::Nosh;
use IPC::Nosh::IO;

our @out = ();
our @err = ();

my $argv = \@ARGV;

const our %goenvironment => (
    goos       => lc( `uname -s` =~ s/[\n\r]+//rg ),
    goarch     => lc( `uname -m` =~ s/[\n\r]+//rg =~ s/x86_64/amd64/rg ),
    gohostos   => lc( `uname -s` =~ s/[\n\r]+//rg ),
    gohostarch => lc( `uname -m` =~ s/[\n\r]+//rg =~ s/x86_64/amd64/rg ),
    goarm64    => undef,
    goarm      => undef,
    goamd64    => undef
);

const our %goarg_def => (
    x          => 1,
    ldflags    => '-compressdwarf=false',
    buildmode  => 'pie',
    mod        => 'readonly',
    modcacherw => 1
);

const our $CLEAN_PREBUILD => qr'pre|prior|before|start|each|once'xxi;
const our $CLEAN_FREQ     => qr'(?::(once|every|each))?';

const our $CLEAN_POSTBUILD => qr'^(
  (?:post|after|success|fail
     $CLEAN_FREQ)
   |(?:each|every)
   |exit
  )$'xxi;

our %cliopts = ( %goenvironment, %goarg_def, clean => ['pre'] );

GetOptionsFromArray(
    $argv,
    \%cliopts,
    ( map { "$_=s" } keys %goenvironment ),
    (
        map { ( $goarg_def{$_} !~ /^(1|0)$/ || !$goarg_def{$_} ) ? "$_=s" : $_ }
          keys %goarg_def
    ),
    "clean=s@",
    '<>' => sub ($barearg) {
        $cliopts{srcdir} = path($barearg)->assert(
            sub {
                $_->is_dir;
            }
        );
    }
);

push $cliopts{clean}->@*, map { split /,/, $_ } $cliopts{clean}->@*;

my $debug = $cliopts{debug} || $ENV{DEBUG};

foreach my ( $key, $val ) ( %cliopts{ map { lc $_ } keys %goenvironment } ) {
    warn Dumper( $key, $val ) if $debug;
    $ENV{ uc $key } = $val    if $val;
}

my @goarg;

foreach my ( $k, $v ) ( %cliopts{ keys %goarg_def } ) {
    if ( $v =~ /^(1|0)$/ && $v == 1 ) {
        push @goarg, "-$k";
    }
    elsif ($v) {
        push @goarg, "-$k", $v;
    }
}

# say STDERR Dumper(
our $dbg_state_prebuild = {
    argv          => $argv,
    cliopts       => \%cliopts,
    goarg         => \@goarg,
    goenvironment => \%goenvironment,
    ENV           => { %ENV{ keys %goenvironment } }
};

# );

dmsg($dbg_state_prebuild);

sub clean ($aref) {
    ...;

    foreach my $val (@$aref) {
        if ( $val =~ $CLEAN_PREBUILD ) {

        }
        elsif ( my @when = ( $val =~ $CLEAN_POSTBUILD ) ) {
            if ( scalar @when == 2 ) {
                if ( $when[0] =~ $CLEAN_FREQ ) {

                }
            }
        }
    }
}

sub build {
    $CWD = $cliopts{srcdir};
    our $run = run( [ qw(go install), @goarg ] );
    dmsg($run);
    $run;
}

our $run = build();
exit $run->status;
