#!/usr/bin/env perl

use utf8;
use v5.40;

use File::chdir;
use Getopt::Long;

use lib './lib';

use BS::Package::Meta::Ext::pactree;

Getopt::Long::Configure("bundling");

our %opts = ();

GetOptions(\%opts,"pkgbuild-repo|pkgmeta");

#BS::Package->new(name => $ARGV[0], dir => $CWD);
say BS::Package::Meta::Ext::pactree->list_deps($ARGV[0], sep => $ARGV[1] // "\n");
