#!/usr/bin/env perl
use Object::Pad;

use lib './lib';

our $class = class :does(App::BS::Common)
                   :does(BS::Package::Meta::Ext::pactree) {
  use utf8;
  use v5.40;

  use File::chdir;
  use Getopt::Long;

  use lib './lib';

  method print_deps (%args) {
    foreach my $pkg ($self->queue->@*) {
      say __PACKAGE__->list_deps($pkg, $self->cliopts->%*, %args)
    }
  }
};

our %opts = ();
our $app = $class->new( getopts => [ "pkgbuild-repo|pkgmeta=s"
                                   , "seperator|sep=s"
                                   , "sort|print-order=s"
                                   , "optdepends-depth|optdep-max=i"
                                   , "delimiter=s" ]
                      , optdest => \%opts );

$app->print_deps(%opts)
