#!/usr/bin/env perl
use Object::Pad;

use lib 'lib';

package pkgdepends;
class pkgdepends :isa(App::BS::CLI)
                 :does(BS::Ext::pactree)
                 :does(BS::alpm) {
  use utf8;
  use v5.40;

  use Pod::Usage;
  use Getopt::Long qw(:config auto_abbrev permute bundling);

  use Inline C => config =>
    enable => autowrap =>
    myextlib => '/usr/lib/libalpm.so.15' =>
    libs => '-lalpm -lalpm_list -lalpm_depends -lalpm_packages';

  Getopt::Long::Configure ("bundling");

  field $queue :mutator :param = [];

  ADJUST {
    GetOptions($self->cliopts
      , $self->getopts_setup->@*, "debug+"
      , "version" => sub { VersionMessage() }
      , "help" => sub { HelpMessage() })
  }

  method run (%runopts) {
    $self->print_self if $ENV{DEBUG};

    foreach my $pkg (@$queue) {
      state $sync = $self->cliopts->{sync};

      print __CLASS__->list_deps( $pkg, $self->cliopts->%*, %runopts
                                      , sync => $sync )
        , $pkg ne $$queue[-1]
            ? ($self->cliopts->{delimiter} // "\n\n")
            : "\n";

      $sync = 0 unless $self->cliopts->{sync} == -1
    }
  }
}

package main;

use utf8;
use v5.40;

use Inline C => config =>
  enable => autowrap =>
  myextlib => '/usr/lib/libalpm.so.15' =>
  libs => '-lalpm';

our %opts = (
  unique => 1,
  sync => 1,
  order => 'asc'
);

our @queue;
our $app = pkgdepends->new(getopts => [ "pkgbuild-repo|pkgmeta:s"
                                      , "seperator:s"
                                      , "order|sort-direction|print-order:s"
                                      , "optional|o:i"
                                      , "depth|max-depth:i"
                                      , "delimiter:s"
                                      , "sync!"
                                      , "unique"
                                      , "<>" => \&handle_barearg ],

                           argv  => \@ARGV,
                           dest  => \%opts,
                           queue => \@queue);

sub handle_barearg ($str) {
  if (length $str == 1 && $ARGV[-1] eq $str) {
    $opts{seperator} = $str
  }
  else {
    push @queue, $str
  }
}

$app->run;

$app->print_self if $ENV{debug}
