#!/usr/bin/env perl

use utf8;
use v5.40;

use File::chdir;
use Getopt::Long;
use List::Util qw(uniqstr);
use IPC::Run3;

use BS::Package;

Getopt::Long::Configure("bundling");

our %opts = ();

GetOptions(\%opts,"pkgbuild-repo|pkgmeta-repo");

#BS::Package->new(name => $ARGV[0], dir => $CWD);
BS::Package->list_deps($ARGV[0], $ARGV[1] // '\n');
