#!/usr/bin/env perl

use Object::Pad ':experimental(:all)';

class BS::App::pkgbase {

    use utf8;
    use v5.40;

    use TOML::Tiny;
    use Const::Fast;
    use Getopt::Long qw(:config no_ignore_case);

    use BS::Common;
    use BS::Ext::expac;
    use BS::Ext::pacsift;

    const our $pkgname_common_re => qr'[^.-]{1}[a-z0-9@_+.-]+?';

const our $pkgprefix_re => qr/(?:(lib)\:)?/;

const our $pkgstr_re => qr/^$pkgprefix_re
          		           ($pkgname_common_re(\.so(?:\.[0-9]+)?)
			              | $pkgname_common_re )
                          /xxi;

const our $epoch_re  => qr'([0-9]+?):'xi;
const our $pkgver_re => qr'([^\s:/\-]+?)'xi;
const our $pkgrel_re => qr'([0-9]+?)'xi;
const our $arch_re   => qr'(any|aarch64|i368|i638|(?:x86_64(?:_v3)?))'xi;
const our $pkgext_re => qr'(pkg.tar.(?:zst|xz|gz|bz2|zip))'xi;

const our $pkgfile_re => qr'$pkgstr_re
                            -(?:$epoch_re:)?
                            $pkgver_re-$pkgrel_re
	               		    -$arch_re
			                .$pkgext_re
			               'xxi;

const our $pkgspec_re => qr'';

    #const our $DEBUG        => $ENV{DEBUG}        // 0;
    const our $SHORTCIRCUIT => $ENV{SHORTCIRCUIT} // 0;

    const our $CONFIG => class {
        field $path   = '/etc/bs/config.toml';
        field $fields = {
            makepkg_conf => {
                default => '/etc/makepkg.conf',
                type    => 'file',

            },
            pacman_conf => {
                default => '/etc/pacman.conf',
                type    => 'file',
            },
        };

        ADJUSTPARAMS($params) {
            ...
        };

        method load_config : common {
        }
    };

    field $argv : param;
    field $queue  = [];
    field $opts   = {};
    field $config = $CONFIG->new( path => $$opts{config_file} );

    ADJUSTPARAMS($params) {
        $argv, $opts, 'unique!', 'resolve-tree', 'verbose+', 'debug+',
          '<>' => sub ($arg) { push @$queue, $arg }
    };

    method env_to_config {

        # Is $val alisaed?
        foreach my ( $key, $val ) ( $config->fields->%* ) {
            if ( $ENV{ uc($key) } ) {
                $$config{$key} = $ENV{$key};
            }
            else {
                my $envkey = 'BS_' . ( $key =~ s/_//r )[0];
                if ( my $val = $ENV{$envkey} ) {
                    $$config{$key} //= $val;
                }

            }
        }

    }

    method run {
    }
}

package pkgbase;

class pkgbase : isa(BS::App::pkgbase);
