#!/usr/bin/env perl

package pkgbase;
use Object::Pad qw(:experimental(:all));

use lib 'lib';

class Pkgbase
  : isa(App::BS::CLI) : does(BS::Ext::pacman) : does(App::BS::CLI::Barearg) :
  does(App::BS::Common);

use utf8;
use v5.40;

use Carp;
use IPC::Run3;
use List::Util qw(any uniqstr all);
use Syntax::Keyword::MultiSub;
use Syntax::Keyword::Dynamically;
use Syntax::Keyword::Try;
use Const::Fast;

const our $VALID_PKG_RE_CCLASS_START => "a-zA-Z0-9\@_\+";

const our $VALID_PKG_RE_NB =>
qr/[$VALID_PKG_RE_CCLASS_START]{1}[$VALID_PKG_RE_CCLASS_START\.\-]+(\.so)|[$VALID_PKG_RE_CCLASS_START]{1}[$VALID_PKG_RE_CCLASS_START\.\-]+/;

const our $PACINFO_SO_PREFIX => qr/(?:lib\:)?/;
const our $DEP_SO_RE         => qr/\.so/;

const our $VALID_DEPIDEN_RE =>
  qr/$PACINFO_SO_PREFIX($VALID_PKG_RE_NB)(?:$DEP_SO_RE)?/;

const our $DEP_ATTRSEP_RE => qr/(?:\=)|(?:[\<\>]\=?)|(?:(?:\:)|(?:[\.\-]{1}))/;

const our $PKGVER_FORBIDDENCH => quotemeta(':/-') . '\s';
const our $PKGVER_RE          => qr/[^$PKGVER_FORBIDDENCH]+/;

const our $DEP_ATTR_RE =>
  qr/^$VALID_DEPIDEN_RE(?:\s*($DEP_ATTRSEP_RE)(?:\s*)($PKGVER_RE|.+))?\n?$/;

BS::Common::dmsg $DEP_ATTR_RE, $PKGVER_FORBIDDENCH, $PKGVER_RE,
  $DEP_ATTRSEP_RE, $VALID_DEPIDEN_RE;

method pacman_query : common ($str, %opts) {
    const my $FILEDB_RE      => qr/files?/;
    const my $REPOPKG_SEP_RE => qr/\//;

    my $res =
      $opts{database} && $opts{database} =~ $FILEDB_RE
      ? BS::Ext::pacman->file_query($str)
      : BS::Ext::pacman->pkg_query($str);

    my $match = $res->out->[0];
    chomp $match;

    [ split /$REPOPKG_SEP_RE/, $match ];
}

method parse_pkgstr : common ($pkgstr, %opts) {
    my ( $depname, $soext, $sep, $attr ) = $pkgstr =~ $DEP_ATTR_RE;
    my %pkgstub = ();

    $pkgstub{name} = $depname;

    if ($sep) {
        if ( $sep ne ':' ) {
            $pkgstub{version} = $attr;
            $pkgstub{cmp_op}  = $sep;
            $pkgstub{file}    = $depname if $soext;
        }
        elsif ( $sep eq ':' ) {    # Optional dependency most likely
                                   # Will have parsed that out elsewhere
            $pkgstub{description} = $attr;
            $pkgstub{name}        = $depname;
        }
    }

    if ( $soext || $opts{file} ) {
        $pkgstub{file} //= $depname;

        @pkgstub{qw(repo name)} =
          $class->pacman_query( $depname, database => 'file' )->@*;
    }

    BS::Common::dmsg( $depname, $soext, $sep, $attr, pkgstub => \%pkgstub )
      if $ENV{DEBUG};

    \%pkgstub;
}

method parse_pacinfo_line : common ($line, %opts) {
    const my $DEPKEY_RE => qr/^(Requires|Optional Deps)$/i;

    my ( $key, $value ) = map {
        $_ =~ s/$BS::Common::TRIM_RE/$1/;
        $_
    } ( split /:/, $line, 2 );

    return undef unless $key && $value;

    $key = lc($key);
    $key =~ s/[^a-z0-9]+/_/;

    $value = $class->pkgbase(
        $class->parse_pkgstr( ref $value eq 'ARRAY' ? $$value[0] : $value ),
        %opts )
      if ( $opts{resolve_deps} // 0 ) && $key =~ $DEPKEY_RE;

    $key, $value;
}

method parse_pacinfo : common ($aref, %opts) {
    const my @VALID_KEYS => qw(Name Base Repository);

    const my $VALID_KEY_RE => map { qr/^($_)$/i } join '|',
      (@VALID_KEYS);

    my $pacinfo_href = {};

    foreach my $line (@$aref) {
        chomp $line;

        $line =~ s/$BS::Common::TRIM_RE/$1/;

        my ( $key, $val ) = $class->parse_pacinfo_line( $line, %opts );

        next unless $key && $val;

        if ( $$pacinfo_href{$key} ) {
            next
              if ( $opts{no_dupes}
                && $opts{dest}->{$key}
                && $$pacinfo_href{$key} eq $opts{dest}->{$key} );

            $$pacinfo_href{$key} = [ $$pacinfo_href{$key} ]
              if ref $$pacinfo_href{$key} ne 'ARRAY';

            unshift $$pacinfo_href{$key}->@*, $val;
        }
        else {
            $$pacinfo_href{$key} = $val;
        }
    }

    $pacinfo_href;
}

method pkgbase : common ($pkgstr, %opts) {
    my $base = $class->pacinfo( $pkgstr, %opts )->{base};
    ref $base eq 'ARRAY' ? $$base[0] : $base;
}

method handle_barearg ($str) {
    if ( length $str == 1 && $ARGV[-1] eq $str ) {
        $self->cliopts->{seperator} = $str;
    }
    else {
        push $self->queue->@*, $str;
    }
}

method pacinfo : common ($pkgstr, %opts) {
    my ( @out, $err );
    run3 [ 'pacinfo', $pkgstr ], \undef, \@out, \$err;
    $class->parse_pacinfo( \@out, %opts );
}

method run {
    my @pkgbase = ();

    const my $DEFORDER_RE => qr/^asc.*/i;

    state $altorder =
      ( $self->cliopts->{default_order} // 'asc' ) =~ $DEFORDER_RE
      ? 'desc'
      : 'asc';

    state $altorder_re = qr/^($altorder|r).*/i;

    foreach my $pkgstr ( $self->queue->@* ) {
        state $arch_ptn_str = $self->env->{arch}->@*;
        const my $PKGARCH_RE => qr/$arch_ptn_str/;

        const my $PKGVER_RE => qr/()/;

        const my $PKGEXT_REGESC =>
          quotemeta( $self->env->{pkgext} // $ENV{PKGEXT} );

        const my $PKGEXT_RE => qr/$PKGEXT_REGESC$/i;

        if ( $pkgstr =~ $PKGEXT_RE ) {
            if ( my $pkgfile = BS::Path->if_exists($pkgstr) ) {
                $pkgstr = $pkgfile->basename(
                    ext => ( $self->env->{pkgext} // $ENV{PKGEXT} ) );
            }
            else {
                const my $S_PKGSTR_ISFILE_404 =>
                  "'$pkgstr' was provided as a package file but was not "
                  . "found in the current working directory!";

                carp $S_PKGSTR_ISFILE_404;

                $pkgstr =~ s/$PKGEXT_RE//i;
            }
        }

        my $pkgstub = Pkgbase->parse_pkgstr( $pkgstr, $self->cliopts->%* );
        my $pkgbase = Pkgbase->pkgbase( $$pkgstub{name}, $self->cliopts->%* );

        BS::Common::dmsg {
            pkgstr  => "$pkgstr",
            pkgstub => $pkgstub,
            pkgbase => $pkgbase
        };

        push @pkgbase, $pkgbase;
    }

    @pkgbase = $self->cliopts->{unique} ? uniqstr @pkgbase : @pkgbase;

    @pkgbase =
      ( $self->cliopts->{order} !~ $altorder_re )
      ? @pkgbase
      : reverse @pkgbase;

    say join $self->cliopts->{sep} // ' ',
      $self->cliopts->{reverse} ? reverse @pkgbase : @pkgbase;
}

our %opts = (
    unique => 1,
    sync   => 1,
    order  => 'asc'
);

package main;

our @queue;

my $app = Pkgbase->new(
    getopts => [
        "pkgbuild-repo|pkgmeta:s",            "seperator:s",
        "order|sort-direction|print-order:s", "optional|o:i",
        "reverse|r",                          "depth|max-depth:i",
        "delimiter:s",                        "sync!",
        "fetch",                              "unique!",
        "updpkgsums",                         "update!",
    ],
    argv  => \@ARGV,
    dest  => \%opts,
    queue => \@queue
)->run;
