#!/usr/bin/env perl

use Object::Pad;

use utf8;
use v5.40;

our $PkgBuild = class :isa(App::BS::pkgbuild) { 
  #field @instances;
  field @packages;
  #field $argv :param = \@ARGV;
  field $opts = {};

  method run {
    __CLASS__->buildpkgs
  }
};

our $pkgbuild = $PkgBuild->new(argv => \@ARGV);
$pkgbuild->run

#my $pkgbuild = App::BS::pkgbuild->new(factory => 1)
#my $pkgbuild = App::BS::pkgbuild->buildpkgs(@packages)
