#!/usr/bin/env perl

use Object::Pad ':experimental(:all)';

package pkgtree;

class pkgtree;

use utf8;
use v5.40;

no warnings 'experimental::re_strict';
use re 'strict';

use lib 'lib';

use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case auto_abbrev bundling long_prefix_pattern=--?);

use Const::Fast;
use List::Util qw'first uniq none';
use IPC::Nosh  qw'';
use IO::Handle::Common;
use PadWalker;
use Syntax::Keyword::Dynamically;

const our @REPO_DEFAULT => qw(
  universe
  core
  extra
);

const our %FIELD_MAP => (
    base                 => '%e',
    arch                 => '%a',
    backup_files         => '%B',
    build_date           => '%b',
    conflicts_nover      => '%C',
    depends_on           => '%D',
    description          => '%d',
    depends_on_nover     => '%E',
    optional_deps        => '%O',
    optional_deps_nodesc => '%o',
    filename             => '%f',
    signature            => '%g',
    groups               => '%G',
    conflicts_with       => '%H',
    md5sum               => '%s',
    sha256sum            => '%h',
    download_size        => '%k',
    licences             => '%L',
    install_size         => '%m',
    name                 => '%n',
    required_by          => '%N',
    version              => '%v',
    url                  => '%u',
    replaces             => '%T',
    replace_nover        => '%R',
    provides_nover       => '%S',
    provides             => '%P',
    packager             => '%p',
    package_valid_method => '%V',
    'literal_%'          => '%%',
);

const our @SORT_ALLOW => qw( buildorder );

const our %RUN_DEFAULT => (
    autochomp => 1,
    err       => sub ( $line, @ ) {
        say STDERR $line;
    }
);

const our $ver_req => qr/([=<>]{1}|(?:[<>]=)){,2}/x;

const our $pkgname_re => qr/
([a-z0-9_@+][a-z0-9_@+.-]+)
 (?:
   ([\s-]|[=<>]{1}|[<>]=)
   ([^\s:\/\\-]+?)
 )?/xi;

const our $soname_re => qr/(.+\.so)=([0-9-].+)/xx;

field $in : param;

field $buildorder : param = 1;

field $sortby  : param = qw'buildorder';
field $sortdir : param = 'desc';

# field $asc;
# field $desc;
# field $reverse;

field $reversedeps : param = 0;
field $repo        : param = \@REPO_DEFAULT;
field $field       : param : accessor = [];

# ADJUST : params (%param) {
#     my $fieldin = delete $param{field};
#     if ( $fieldin && refstr($fieldin) eq "ARRAY" ) {
#         @$field = ( uniq( @$field, @$fieldin ) );
#     }

#     # delete $param{field}
# };

# ADJUST : params (%params)) { my $fieldset = [ uniq $self->field->@*, @$field ]; $self->adjust($self->$adjust()) };
field $fmtstr : param : accessor = '%e';

# Default is hybrid: will do expac -Ss if pkgstr has regex meta-characters
field $exact  : param : accessor = 0;
field $regex  : param : accessor = 1;
field $sep    : param = ' ';
field $unique : param = 1;
field $depth  : param = undef;
field $pkgtree = {};

field $db             : param = 'sync';
field $filedb_updated : accessor;
field $pkgdb_updated  : accessor;

field $verbose    : param    = 0;
field $extcmd_log : accessor = [];

method run ( $cmd, %opt ) {
    my $run = IPC::Nosh::run( $cmd, %RUN_DEFAULT, %opt );
    dmsg $cmd, $run->status;
    push @$extcmd_log, $run;

    $run;
}

method pkgfield ( $pkgin, $field, %opt ) {
    my $op = '-S';
    $op .= 's' unless $opt{exact};

    ( $pkgin, $field, $opt{dest} ) = ARRAY( $pkgin, $field, $opt{dest} );

    my @cmd = ( 'expac', $op, ( join ',', uniq @FIELD_MAP{@$field} ) );

    my $outh = sub ( $line, @ ) {
        push $opt{dest}->@*, grep {
            my $new = $_;
            none { $_ eq $new } $opt{dest}->@*
        } split /\s/, $line;
    };

    my $run;

    if ( $opt{exact} ) {
        $run = $self->run( [ @cmd, @$pkgin ], out => $outh );
    }
    else {
        foreach my $pkgstr (@$pkgin) {
            $self->run( [ @cmd, $pkgstr ], out => $outh );
        }
    }

    $opt{dest}->@*;
}

method pkgbase ( $pkglist, %opt ) {
    $self->pkgfield( $pkglist, 'base', %opt );
}

method pkgname ( $pkglist, %opt ) {
    $self->pkgfield( $pkglist, 'name', %opt );
}

sub refstr : prototype($) ($ref) {
    reftype($ref) || "";
}

sub ARRAY : prototype(@) (@in) {
    my @ret;

    foreach my ($var) (@in) {
        $var //= [];
        my $type = reftype($var);

        if ( !$type ) {
            push @ret, [$var];
        }
        elsif ( $type ne 'ARRAY' ) {
            my $name = PadWalker::var_name( 0, $var );
            die "\$name must be an ARRAY ref or a scalar value. (Got: $type)";
        }
        elsif ( $type eq 'ARRAY' ) {
            push @ret, $var;
        }
    }

    @ret;
}
*array = \&ARRAY;

method pacman_provides ( $pkg, %opt ) {

    # die "\$opt{dest} must be an ARRAY. (Got: )" . reftype( $opt{dest} )
    #   if reftype( $opt{dest} ) ne 'ARRAY';

    ( $pkg, $opt{dest} ) = array( $pkg, $opt{dest} );

    # sudo pacman -Sy --print-format '%P' ffmpeg-git
    $self->run(
        [ qw(pacman -S --print-format '%P'), pacman_updarg($db), $pkg ],
        out => sub( $line, @ ) {
            $self->group_pkgstr( $line, $opt{dest} );
        }
    );
}

method pacman_updarg ( $db, %opt ) {
    my $lastupdate = $db eq 'file' ? 'filedb_updated' : 'pkgdb_updated';
    if ( !$self->$lastupdate || $opt{force} ) {
        $self->$lastupdate(time);
        return '-y';
    }
    undef;
}

method pacman_pkgname( $pkglist, %opt ) {
    ( $pkglist, $opt{dest} ) = ARRAY( $pkglist, $opt{dest} );

    my $pkgre = '^(' . ( join '|', uniq @$pkglist ) . ')$';

    my @cmd = qw(pacman -Sqs);

    if ( my $arg = $self->pacman_updarg( 'package', force => $opt{update_db} ) )
    {
        unshift @cmd, 'sudo';
        push @cmd, $arg;
    }

    push @cmd, $pkgre;

    my $run = $self->run(
        \@cmd,
        out => sub( $line, @ ) {
            if ( my ($name) = ( $line =~ /^$pkgname_re/ ) ) {

                # dmsg $name, $line, $pkgname_re;
                push $opt{dest}->@*, $name;
            }
        }
    );

    fatal( '`' . ( join ' ', @cmd ) . "` exited with " . $run->status )
      if $run->status > 0;

    # dmsg \%opt, $pkgre, \@cmd;

    $opt{dest}->@*;
}

method pacman_files ( $filelist, %opt ) {
    ( $filelist, $opt{dest} ) = array( $filelist, $opt{dest} );

    my @cmd = qw(pacman -Fq);
    if ( my $arg = $self->pacman_updarg( 'package', force => $opt{update_db} ) )
    {
        unshift @cmd, 'sudo';
        push @cmd, $arg;
    }

    my $run = $self->run(
        [ @cmd, uniq @$filelist ],
        out => sub ( $line, @ ) {
            say $line if $verbose;
            if ( my ( $repo, $name ) = $line =~ m!([^/]+)/(.+)!g ) {
                push $opt{dest}->@*, $name
                  if none { $_ eq $name } $opt{dest}->@*;
            }
        }
    );

    # dmsg \@cmd;

    $opt{dest}->@*;
}

method pactree ( $pkglist, %opt ) {
    my @res = ();

    my $dest = $opt{dest} //= { pkg => [], file => [] };
    $opt{db} //= 'sync';
    ($pkglist) = ARRAY($pkglist);

    my @pkgname = ();
    my @file    = ();

    foreach my $pkgstr (@$pkglist) {

        # my @cmd     = ( qw(pactree -lu), $pkgstr );
        my @cmd =
          ( qw(pactree -lu), ( $opt{db} eq 'sync' ? qw'-s' : () ) );

        push @cmd, ( '--depth', $depth ) if defined $depth ;

        my $run = $self->run(
            [ @cmd, $pkgstr ],
            out => sub ( $line, @ ) {

                if ( my ( $soname, $sover ) = $line =~ $soname_re ) {
                    push @file, $soname
                      if none { $_ eq $soname } @file, $$dest{file}->@*;
                }
                elsif ( my ( $name, $cmp, $ver ) = $line =~ $pkgname_re ) {
                    push @pkgname, $name
                      if none { $_ eq $name } @pkgname, $$dest{pkg}->@*;
                }
                else {
                    error
"'$pkgstr' does not seem to be a shared object or package name/base.";
                }
            }
        );
        push @res, $run;

        # dmsg \@cmd;

        # Get canon/current pkgname (example dependency package has been
        # replaced but pactree returns name it was built with)

        #push $opt{dest}->@*, @pkgname;
    }

    push $$dest{pkg}->@*, uniq $self->pacman_pkgname( \@pkgname )
      if scalar @pkgname;    #$$dest{pkg}->@*;

    push $$dest{pkg}->@*, uniq $self->pacman_files( \@file )
      if scalar @file;

    $opt{dest}->%*;
}

method arch_rebuild_order( $pkgname_aref, %opt ) {
    my $ordered = $opt{dest} // [];

    my $repostr = '--repos=' . join ',',
      ( $opt{repo} && $opt{repo} eq 'ARRAY' ? $opt{repo}->@* : @$repo );

    dynamically $reversedeps = $opt{reversedeps};

    my $run = $self->run(
        [
            qw'arch-rebuild-order',                         $repostr,
            ( $reversedeps ? () : '--no-reverse-depends' ), @$pkgname_aref
        ],
        out => sub ( $line, @ ) {
            push @$ordered, split /\s/, $line;
        },
        autochomp => 1
    );

    @$ordered;
}

method resolve ( $pkglist //= $in, %opt ) {

    dmsg $pkglist, \%opt;

    my @in_pkgname;
    $self->pacman_pkgname( $pkglist, %opt, dest => \@in_pkgname );

    dmsg \@in_pkgname;

    my %pactree = ( pkg => [], file => [] );
    $self->pactree( \@in_pkgname, dest => \%pactree, exact => 1 );

    # @pactree = uniq @pactree if $opt{unique} // $unique;
    dmsg \%pactree;

    my @ordered;
    $self->arch_rebuild_order( $pactree{pkg}, dest => \@ordered )
      if $opt{buildorder} // $buildorder;

    dmsg \@ordered;

    if ( !scalar $field ) {
        error
"Outputting package bases. For package names run with '--field=name' or '--names'";
    }

    $self->pkgfield(
        ( scalar @ordered ? \@ordered : $pactree{pkg} ),
        (
            first { $_ && ( reftype($_) eq 'ARRAY' ) && scalar(@$_) > 0 }
              ( $opt{field}, $field, ['base'] )
        ),
        exact => 1
    );
}

method cli : common ($argv = \@ARGV, %opt) {
    my %clidest = (
        in    => [],
        prune => 'input',
        sep   => ' ',
        depth => undef,
        field => ['base'],
        'db'  => 'sync'
    );

    GetOptionsFromArray(
        $argv,
        \%clidest,

        # output fields and format
        # 'base', 'name',
        'field=s@',
        'fmtstr=s',

        # database to search with pactree, expac and pacman
        'db:s',    # sync or local
        'sync',
        'local',

        # resultset print order
        'sort-by|order-by=s@',
        'build-order|rebuild-order|arch-rebuild-order!',
        'sort-direction|order',
        'asc', 'desc',
        'sep|seperator=s',
        'depth=i',

        # input search scope
        'exact!',
        'regexp',

        # output verbosity control
        'debug+',
        'verbose+',
        'quiet+',

        # enabled repositories (for sync db)
        'repository=s@',

        # print dependents of input packages
        'reversedeps|reverse-depends!',

        # prune/filter packages at different stages of resolution
        "prune:s",
        "variant|choose|chosen|wanted:s",

        # input packages
        '<>' => sub ($barearg) {
            dmsg $barearg;
            push $clidest{in}->@*, $barearg;
        }
    );

    $clidest{in}->@* = uniq $clidest{in}->@* if $clidest{prune};

    my $self = $class->new( %clidest, %opt );
    dmsg $self, \%clidest;

    my @pkgtree = $self->resolve;

    # dmsg \@pkgtree;

    say join $clidest{sep}, @pkgtree;
}

package pkgtree::CLI;

use utf8;
use v5.40;

pkgtree->cli( \@ARGV )
