#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';
use lib 'lib';

package App::BS::repofix;    #a: does(BS::Run);

class App::BS::repofix;

use v5.40;

use BS::Common;
use BS::Run;
use IPC::Run3;

our @outbuff;
our @errbuff;

field $dir;
field $remote;

ADJUST : params ( :$dir ,:$cloneuri ) {...};

method reset_remotes : common ($dirlist, %opts) {
    foreach my $dir (@$dirlist) {
        $class->new($dir);
    }
}

# sub outh ($line) {
#     push @outbuff, $line;
#     chomp $line;
#     say "▶ $line";
# }

