#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package srcinfo::cli;
use lib 'lib';

class srcinfo::cli : does(BS::Common);

use utf8;
use v5.40;

use parent 'Exporter';
use vars '@EXPORT';

use Cwd          qw( cwd );
use Getopt::Long qw(GetOptionsFromArray :config no_ignore_case auto_abbrev);
use Path::Tiny;
use Const::Fast;
use List::Util qw'uniq first any';
use BS::Package::SRCINFO;

use IPC::Nosh;
use IPC::Nosh::Common;

const our $ENV_RE => qr/^(.*sh|env(?:vironment)?|export)$/;

const our %OUTFMT => (

    $ENV_RE => 'srcinfo::bash'
    , # POSIX will probably be the only other in this category but I think that's basically just a .SRCINFO file without changes
    json => sub ( $srcinfo, $inref, %opt ) {
        $srcinfo->as_json;
    },
    toml          => 'TOML::Tiny',
    yaml          => 'YAML::Tiny',
    storable      => '',
    'data-dumper' => ''
);
const our $execdir => path(cwd);

field $clispec : param          : reader;
field $cliopt  : param(clidest) : reader;
field $argv    : param          : reader;

field $infile //= path( $execdir->absolute . '/.SRCINFO' );

field $outfile {
    $infile unless any { $_ } @$cliopt{qw(readonly noop no-update)}
};

field $field = $$cliopt{field};
field $format : reader = $$cliopt{format} // { %OUTFMT{$ENV_RE} };

field $srcinfo_href = {};

field $srcinfo : reader;

ADJUSTPARAMS($params) {
    $self->getopt;
    $self->load;
    if ( $$cliopt{format} ) {
        if ( $$cliopt{format} =~ $ENV_RE ) {
            $format = $OUTFMT{$ENV_RE};
        }
        elsif ( my $key = first { $format eq $_ } keys %OUTFMT ) {
            $format = $OUTFMT{$key}

            # Init serializer with settings
        }
        else {
            danger("Option --format=$$cliopt{format} is not valid");
            $format = $OUTFMT{$ENV_RE};
        }
    }
}

method getopt (
    $argv    = $self->argv,
    $optspec = $self->clispec,
    $optdest = $self->cliopt, %opt
  )
{
    my @getoptspec = ();

    foreach my ( $k, $v ) (@$optspec) {
        if ( $k eq '<>' && ref $v eq 'CODE' ) {
            my $ogsub = $v;
            $v = sub ($barearg) {
                $ogsub->( $self, $barearg );
            };

            push @getoptspec, ( $k, $v );
        }
        else {
            my $opt = "$k";    #=$v"
            $opt .= "=$v" unless $v eq 'f';
            push @getoptspec, $opt;
        }
    }

    GetOptionsFromArray( ( $argv // \@ARGV ), $optdest, @getoptspec );
}

# method pkgfile_glob ( $srcinfo, $pkgver, $arch ) {
#     my $pkgver_str;

#     dmsg $srcinfo, $pkgver;

#     if ($pkgver) {
#         if (
#             my $pkgver_href =
#             ( ( $pkgver && ref $pkgver eq 'HASH' ) ? \%$pkgver : undef ) // (
#                 $pkgver eq $ENV{PKGVER_CURR}
#                 ? { $srcinfo->%{qw'epoch ver rel'} }
#                 : undef
#             )
#           )
#         {
#             $pkgver_str .= "$$pkgver_href{epoch}:" if $$pkgver_href{epoch};
#             $pkgver_str .= $$pkgver_href{ver};
#             $pkgver_str .= "-$$pkgver_href{rel}" if $$pkgver_href{rel};
#         }
#         elsif ($pkgver) {
#             $pkgver_str = $pkgver;
#         }
#     }
#     my $glob =
#       $$srcinfo{pkgname} eq 'ARRAY'
#       ? '{' . ( join ',', $$srcinfo{pkgname}->@* ) . '}-'
#       : "$$srcinfo{pkgname}"
#       . (
#         ref $$srcinfo{arch} eq 'ARRAY'
#         ? ( $pkgver_str ? " -$pkgver_str-" : "-*" ) . "-{"
#           . ( join ',', $$srcinfo{arch}->@* ) . '}'
#         : "-$$srcinfo{arch}"
#       ) . ".pkg.tar.zst";

#     $glob;
# }

# method fname_wildcard_nover ( $arch = undef )
# {    # pass your own or set to 1 for current
#     pkgfile_glob( $srcinfo_href, undef, $arch );
# }

method as ( $format = $self->format, $field = $self->field ) {
    $srcinfo->as( $format, $field );
}

method cli : common ($argv, $clispec, $dest //= {}, %opt) {
    my $self = $class->new(
        clispec => $clispec,
        argv    => $argv,
        clidest => $dest
    );

    dmsg $self;

    say $self->as( @$dest{qw(format field)} );
    $self;
}

method load ( $in = $infile ) {
    $infile  = $in;
    $srcinfo = BS::Package::SRCINFO->new( file => $in );
}

package main;

use v5.40;

use Path::Tiny;
use IPC::Nosh::Common;

our @clispec = (
    'field|fields|out-fields|outfields|filter|select' => 's{1,}',
    'format|out-format|fmt|of|outfmt'                 => 's',
    'pretty-print!'                                   => 'f',
    '<>' => sub ( $self, $barearg ) {
        my $srcinfo =
          $self->load( path($barearg)->assert( sub { $_->exists } ) );
    }
);

our %cliopt = ( field => [] );

our $cli = srcinfo::cli->cli( \@ARGV, \@clispec, \%cliopt );
dmsg $cli;
