#!/usr/bin/env perl
use Object::Pad qw(:experimental(:all));

package srcinfo;
class srcinfo :isa(App::BS::CLI) :does(App::BS::CLI::Barearg);

use utf8;
use v5.40;

use lib 'lib';

use Path::Tiny;
use Data::Printer;
use Tie::File;
use Time::Moment;
use Time::HiRes;
use Time::Piece;
use BS::Common;
use BS::Ext::expac;
use List::Util qw(any all first);
use Syntax::Keyword::Defer;
use Syntax::Keyword::Dynamically;
use Syntax::Keyword::Try;

our $srcinfo_file = path($ARGV[0]);
our %srcinfo_out;

ADJUSTPARAMS ($params) {

}

method load ($path, %args) {
  srcinfo->load_srcinfo($path, %args)
}

method load_srcinfo :common ($path, %args) {
  srcinfo->new( path => $path, %args )
}

package main;

our %dest;
our $srcinfo = srcinfo->new(argv => \@ARGV, dest => \%dest);

dmsg ({ app => $srcinfo })